/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "/input/DENM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#include "etsi_its_denm_coding/denm_WrongWayDriverContainer.h"

asn_TYPE_member_t asn_MBR_denm_WrongWayDriverContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct denm_WrongWayDriverContainer, wrongWayDriverStationID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_denm_StationID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"wrongWayDriverStationID"
		},
};
static const ber_tlv_tag_t asn_DEF_denm_WrongWayDriverContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_denm_WrongWayDriverContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* wrongWayDriverStationID */
};
asn_SEQUENCE_specifics_t asn_SPC_denm_WrongWayDriverContainer_specs_1 = {
	sizeof(struct denm_WrongWayDriverContainer),
	offsetof(struct denm_WrongWayDriverContainer, _asn_ctx),
	asn_MAP_denm_WrongWayDriverContainer_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_denm_WrongWayDriverContainer = {
	"WrongWayDriverContainer",
	"WrongWayDriverContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_denm_WrongWayDriverContainer_tags_1,
	sizeof(asn_DEF_denm_WrongWayDriverContainer_tags_1)
		/sizeof(asn_DEF_denm_WrongWayDriverContainer_tags_1[0]), /* 1 */
	asn_DEF_denm_WrongWayDriverContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_denm_WrongWayDriverContainer_tags_1)
		/sizeof(asn_DEF_denm_WrongWayDriverContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_denm_WrongWayDriverContainer_1,
	1,	/* Elements count */
	&asn_SPC_denm_WrongWayDriverContainer_specs_1	/* Additional specs */
};

