/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/asm_custom/ASM-PDU-Descriptions.asn \
  asn1/raw/asm_custom/cdd/ITS-Container.asn \
  -t \
  asm \
  -o \
  etsi_its_conversion/etsi_its_asm_conversion/include/etsi_its_asm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
ASM ::=SEQUENCE {
    header	ItsPduHeader,
    generationTime TimestampIts,
    applicationIdentifier ApplicationIdentifier,
    payload		ApplicationSpecificMessage
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_asm_coding/asm_ASM.h>
#include <etsi_its_asm_conversion/convertApplicationIdentifier.h>
#include <etsi_its_asm_conversion/convertApplicationSpecificMessage.h>
#include <etsi_its_asm_conversion/convertItsPduHeader.h>
#include <etsi_its_asm_conversion/convertTimestampIts.h>
#include <etsi_its_asm_msgs/msg/asm.hpp>
namespace asm_msgs = etsi_its_asm_msgs::msg;


namespace etsi_its_asm_conversion {

void toRos_ASM(const asm_ASM_t& in, asm_msgs::ASM& out) {
  toRos_ItsPduHeader(in.header, out.header);
  toRos_TimestampIts(in.generationTime, out.generation_time);
  toRos_ApplicationIdentifier(in.applicationIdentifier, out.application_identifier);
  toRos_ApplicationSpecificMessage(in.payload, out.payload);
}

void toStruct_ASM(const asm_msgs::ASM& in, asm_ASM_t& out) {
  memset(&out, 0, sizeof(asm_ASM_t));
  toStruct_ItsPduHeader(in.header, out.header);
  toStruct_TimestampIts(in.generation_time, out.generationTime);
  toStruct_ApplicationIdentifier(in.application_identifier, out.applicationIdentifier);
  toStruct_ApplicationSpecificMessage(in.payload, out.payload);
}

}
