/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#include "etsi_its_mcm_coding/mcm_Submanoeuvre.h"

asn_TYPE_member_t asn_MBR_mcm_Submanoeuvre_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct mcm_Submanoeuvre, submanoeuvreId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mcm_Identifier1B,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"submanoeuvreId"
		},
	{ ATF_POINTER, 2, offsetof(struct mcm_Submanoeuvre, advisedTrajectory),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mcm_Trajectory,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"advisedTrajectory"
		},
	{ ATF_POINTER, 1, offsetof(struct mcm_Submanoeuvre, advisedTargetRoadResource),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mcm_AdvisedTrrContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"advisedTargetRoadResource"
		},
};
static const int asn_MAP_mcm_Submanoeuvre_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_mcm_Submanoeuvre_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_mcm_Submanoeuvre_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* submanoeuvreId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* advisedTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* advisedTargetRoadResource */
};
asn_SEQUENCE_specifics_t asn_SPC_mcm_Submanoeuvre_specs_1 = {
	sizeof(struct mcm_Submanoeuvre),
	offsetof(struct mcm_Submanoeuvre, _asn_ctx),
	asn_MAP_mcm_Submanoeuvre_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_mcm_Submanoeuvre_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_mcm_Submanoeuvre = {
	"Submanoeuvre",
	"Submanoeuvre",
	&asn_OP_SEQUENCE,
	asn_DEF_mcm_Submanoeuvre_tags_1,
	sizeof(asn_DEF_mcm_Submanoeuvre_tags_1)
		/sizeof(asn_DEF_mcm_Submanoeuvre_tags_1[0]), /* 1 */
	asn_DEF_mcm_Submanoeuvre_tags_1,	/* Same as above */
	sizeof(asn_DEF_mcm_Submanoeuvre_tags_1)
		/sizeof(asn_DEF_mcm_Submanoeuvre_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_mcm_Submanoeuvre_1,
	3,	/* Elements count */
	&asn_SPC_mcm_Submanoeuvre_specs_1	/* Additional specs */
};

