/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_MessageSegmentationInfo_H_
#define	_mcm_MessageSegmentationInfo_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_CardinalNumber3b.h"
#include "etsi_its_mcm_coding/mcm_OrdinalNumber3b.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_MessageSegmentationInfo */
typedef struct mcm_MessageSegmentationInfo {
	mcm_CardinalNumber3b_t	 totalMsgNo;
	mcm_OrdinalNumber3b_t	 thisMsgNo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_MessageSegmentationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_MessageSegmentationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_MessageSegmentationInfo_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
