/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_EnergyStorageType_H_
#define	_mcm_EnergyStorageType_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_EnergyStorageType {
	mcm_EnergyStorageType_hydrogenStorage	= 0,
	mcm_EnergyStorageType_electricEnergyStorage	= 1,
	mcm_EnergyStorageType_liquidPropaneGas	= 2,
	mcm_EnergyStorageType_compressedNaturalGas	= 3,
	mcm_EnergyStorageType_diesel	= 4,
	mcm_EnergyStorageType_gasoline	= 5,
	mcm_EnergyStorageType_ammonia	= 6
} e_mcm_EnergyStorageType;

/* mcm_EnergyStorageType */
typedef BIT_STRING_t	 mcm_EnergyStorageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_EnergyStorageType;
asn_struct_free_f mcm_EnergyStorageType_free;
asn_struct_print_f mcm_EnergyStorageType_print;
asn_constr_check_f mcm_EnergyStorageType_constraint;
jer_type_encoder_f mcm_EnergyStorageType_encode_jer;
per_type_decoder_f mcm_EnergyStorageType_decode_uper;
per_type_encoder_f mcm_EnergyStorageType_encode_uper;
per_type_decoder_f mcm_EnergyStorageType_decode_aper;
per_type_encoder_f mcm_EnergyStorageType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_EnergyStorageType_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
