/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_Shape_H_
#define	_mcm_Shape_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_RectangularShape.h"
#include "etsi_its_mcm_coding/mcm_CircularShape.h"
#include "etsi_its_mcm_coding/mcm_PolygonalShape.h"
#include "etsi_its_mcm_coding/mcm_EllipticalShape.h"
#include "etsi_its_mcm_coding/mcm_RadialShape.h"
#include "etsi_its_mcm_coding/mcm_RadialShapes.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_Shape_PR {
	mcm_Shape_PR_NOTHING,	/* No components present */
	mcm_Shape_PR_rectangular,
	mcm_Shape_PR_circular,
	mcm_Shape_PR_polygonal,
	mcm_Shape_PR_elliptical,
	mcm_Shape_PR_radial,
	mcm_Shape_PR_radialShapes
	/* Extensions may appear below */
	
} mcm_Shape_PR;

/* mcm_Shape */
typedef struct mcm_Shape {
	mcm_Shape_PR present;
	union mcm_Shape_u {
		mcm_RectangularShape_t	 rectangular;
		mcm_CircularShape_t	 circular;
		mcm_PolygonalShape_t	 polygonal;
		mcm_EllipticalShape_t	 elliptical;
		mcm_RadialShape_t	 radial;
		mcm_RadialShapes_t	 radialShapes;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_Shape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_Shape;
extern asn_CHOICE_specifics_t asn_SPC_mcm_Shape_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_Shape_1[6];
extern asn_per_constraints_t asn_PER_type_mcm_Shape_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_Shape_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
