/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_LongitudinalAccelerationValue_H_
#define	_mcm_LongitudinalAccelerationValue_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_LongitudinalAccelerationValue {
	mcm_LongitudinalAccelerationValue_negativeOutOfRange	= -160,
	mcm_LongitudinalAccelerationValue_positiveOutOfRange	= 160,
	mcm_LongitudinalAccelerationValue_unavailable	= 161
} e_mcm_LongitudinalAccelerationValue;

/* mcm_LongitudinalAccelerationValue */
typedef long	 mcm_LongitudinalAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_LongitudinalAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_LongitudinalAccelerationValue;
asn_struct_free_f mcm_LongitudinalAccelerationValue_free;
asn_struct_print_f mcm_LongitudinalAccelerationValue_print;
asn_constr_check_f mcm_LongitudinalAccelerationValue_constraint;
jer_type_encoder_f mcm_LongitudinalAccelerationValue_encode_jer;
per_type_decoder_f mcm_LongitudinalAccelerationValue_decode_uper;
per_type_encoder_f mcm_LongitudinalAccelerationValue_encode_uper;
per_type_decoder_f mcm_LongitudinalAccelerationValue_decode_aper;
per_type_encoder_f mcm_LongitudinalAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_LongitudinalAccelerationValue_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
