/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_McmType_H_
#define	_mcm_McmType_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_McmType {
	mcm_McmType_intent	= 0,
	mcm_McmType_request	= 1,
	mcm_McmType_response	= 2,
	mcm_McmType_reservation	= 3,
	mcm_McmType_termination	= 4,
	mcm_McmType_cancellationRequest	= 5,
	mcm_McmType_emergencyManoeuvreReservation	= 6,
	mcm_McmType_executionStatus	= 7,
	mcm_McmType_offer	= 8
} e_mcm_McmType;

/* mcm_McmType */
typedef long	 mcm_McmType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_McmType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_McmType;
extern const asn_INTEGER_specifics_t asn_SPC_mcm_McmType_specs_1;
asn_struct_free_f mcm_McmType_free;
asn_struct_print_f mcm_McmType_print;
asn_constr_check_f mcm_McmType_constraint;
jer_type_encoder_f mcm_McmType_encode_jer;
per_type_decoder_f mcm_McmType_decode_uper;
per_type_encoder_f mcm_McmType_encode_uper;
per_type_decoder_f mcm_McmType_decode_aper;
per_type_encoder_f mcm_McmType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_McmType_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
