/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ExteriorLights_H_
#define	_mcm_ExteriorLights_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ExteriorLights {
	mcm_ExteriorLights_lowBeamHeadlightsOn	= 0,
	mcm_ExteriorLights_highBeamHeadlightsOn	= 1,
	mcm_ExteriorLights_leftTurnSignalOn	= 2,
	mcm_ExteriorLights_rightTurnSignalOn	= 3,
	mcm_ExteriorLights_daytimeRunningLightsOn	= 4,
	mcm_ExteriorLights_reverseLightOn	= 5,
	mcm_ExteriorLights_fogLightOn	= 6,
	mcm_ExteriorLights_parkingLightsOn	= 7
} e_mcm_ExteriorLights;

/* mcm_ExteriorLights */
typedef BIT_STRING_t	 mcm_ExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_ExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_ExteriorLights;
asn_struct_free_f mcm_ExteriorLights_free;
asn_struct_print_f mcm_ExteriorLights_print;
asn_constr_check_f mcm_ExteriorLights_constraint;
jer_type_encoder_f mcm_ExteriorLights_encode_jer;
per_type_decoder_f mcm_ExteriorLights_decode_uper;
per_type_encoder_f mcm_ExteriorLights_encode_uper;
per_type_decoder_f mcm_ExteriorLights_decode_aper;
per_type_encoder_f mcm_ExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ExteriorLights_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
