/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_CauseCodeChoice_H_
#define	_mcm_CauseCodeChoice_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_SubCauseCodeType.h"
#include "etsi_its_mcm_coding/mcm_TrafficConditionSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_AccidentSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_RoadworksSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_ImpassabilitySubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_AdverseWeatherCondition-AdhesionSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HazardousLocation-SurfaceConditionSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HazardousLocation-ObstacleOnTheRoadSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HazardousLocation-AnimalOnTheRoadSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HumanPresenceOnTheRoadSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_WrongWayDrivingSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_RescueAndRecoveryWorkInProgressSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_AdverseWeatherCondition-ExtremeWeatherConditionSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_AdverseWeatherCondition-VisibilitySubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_AdverseWeatherCondition-PrecipitationSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_SlowVehicleSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_DangerousEndOfQueueSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_VehicleBreakdownSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_PostCrashSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HumanProblemSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_StationaryVehicleSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_EmergencyVehicleApproachingSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_HazardousLocation-DangerousCurveSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_CollisionRiskSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_SignalViolationSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_DangerousSituationSubCauseCode.h"
#include "etsi_its_mcm_coding/mcm_RailwayLevelCrossingSubCauseCode.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_CauseCodeChoice_PR {
	mcm_CauseCodeChoice_PR_NOTHING,	/* No components present */
	mcm_CauseCodeChoice_PR_reserved0,
	mcm_CauseCodeChoice_PR_trafficCondition1,
	mcm_CauseCodeChoice_PR_accident2,
	mcm_CauseCodeChoice_PR_roadworks3,
	mcm_CauseCodeChoice_PR_reserved4,
	mcm_CauseCodeChoice_PR_impassability5,
	mcm_CauseCodeChoice_PR_adverseWeatherCondition_Adhesion6,
	mcm_CauseCodeChoice_PR_aquaplaning7,
	mcm_CauseCodeChoice_PR_reserved8,
	mcm_CauseCodeChoice_PR_hazardousLocation_SurfaceCondition9,
	mcm_CauseCodeChoice_PR_hazardousLocation_ObstacleOnTheRoad10,
	mcm_CauseCodeChoice_PR_hazardousLocation_AnimalOnTheRoad11,
	mcm_CauseCodeChoice_PR_humanPresenceOnTheRoad12,
	mcm_CauseCodeChoice_PR_reserved13,
	mcm_CauseCodeChoice_PR_wrongWayDriving14,
	mcm_CauseCodeChoice_PR_rescueAndRecoveryWorkInProgress15,
	mcm_CauseCodeChoice_PR_reserved16,
	mcm_CauseCodeChoice_PR_adverseWeatherCondition_ExtremeWeatherCondition17,
	mcm_CauseCodeChoice_PR_adverseWeatherCondition_Visibility18,
	mcm_CauseCodeChoice_PR_adverseWeatherCondition_Precipitation19,
	mcm_CauseCodeChoice_PR_violence20,
	mcm_CauseCodeChoice_PR_reserved21,
	mcm_CauseCodeChoice_PR_reserved22,
	mcm_CauseCodeChoice_PR_reserved23,
	mcm_CauseCodeChoice_PR_reserved24,
	mcm_CauseCodeChoice_PR_reserved25,
	mcm_CauseCodeChoice_PR_slowVehicle26,
	mcm_CauseCodeChoice_PR_dangerousEndOfQueue27,
	mcm_CauseCodeChoice_PR_publicTransportVehicleApproaching28,
	mcm_CauseCodeChoice_PR_reserved29,
	mcm_CauseCodeChoice_PR_reserved30,
	mcm_CauseCodeChoice_PR_reserved31,
	mcm_CauseCodeChoice_PR_reserved32,
	mcm_CauseCodeChoice_PR_reserved33,
	mcm_CauseCodeChoice_PR_reserved34,
	mcm_CauseCodeChoice_PR_reserved35,
	mcm_CauseCodeChoice_PR_reserved36,
	mcm_CauseCodeChoice_PR_reserved37,
	mcm_CauseCodeChoice_PR_reserved38,
	mcm_CauseCodeChoice_PR_reserved39,
	mcm_CauseCodeChoice_PR_reserved40,
	mcm_CauseCodeChoice_PR_reserved41,
	mcm_CauseCodeChoice_PR_dontPanic42,
	mcm_CauseCodeChoice_PR_reserved43,
	mcm_CauseCodeChoice_PR_reserved44,
	mcm_CauseCodeChoice_PR_reserved45,
	mcm_CauseCodeChoice_PR_reserved46,
	mcm_CauseCodeChoice_PR_reserved47,
	mcm_CauseCodeChoice_PR_reserved48,
	mcm_CauseCodeChoice_PR_reserved49,
	mcm_CauseCodeChoice_PR_reserved50,
	mcm_CauseCodeChoice_PR_reserved51,
	mcm_CauseCodeChoice_PR_reserved52,
	mcm_CauseCodeChoice_PR_reserved53,
	mcm_CauseCodeChoice_PR_reserved54,
	mcm_CauseCodeChoice_PR_reserved55,
	mcm_CauseCodeChoice_PR_reserved56,
	mcm_CauseCodeChoice_PR_reserved57,
	mcm_CauseCodeChoice_PR_reserved58,
	mcm_CauseCodeChoice_PR_reserved59,
	mcm_CauseCodeChoice_PR_reserved60,
	mcm_CauseCodeChoice_PR_reserved61,
	mcm_CauseCodeChoice_PR_reserved62,
	mcm_CauseCodeChoice_PR_reserved63,
	mcm_CauseCodeChoice_PR_reserved64,
	mcm_CauseCodeChoice_PR_reserved65,
	mcm_CauseCodeChoice_PR_reserved66,
	mcm_CauseCodeChoice_PR_reserved67,
	mcm_CauseCodeChoice_PR_reserved68,
	mcm_CauseCodeChoice_PR_reserved69,
	mcm_CauseCodeChoice_PR_reserved70,
	mcm_CauseCodeChoice_PR_reserved71,
	mcm_CauseCodeChoice_PR_reserved72,
	mcm_CauseCodeChoice_PR_reserved73,
	mcm_CauseCodeChoice_PR_reserved74,
	mcm_CauseCodeChoice_PR_reserved75,
	mcm_CauseCodeChoice_PR_reserved76,
	mcm_CauseCodeChoice_PR_reserved77,
	mcm_CauseCodeChoice_PR_reserved78,
	mcm_CauseCodeChoice_PR_reserved79,
	mcm_CauseCodeChoice_PR_reserved80,
	mcm_CauseCodeChoice_PR_reserved81,
	mcm_CauseCodeChoice_PR_reserved82,
	mcm_CauseCodeChoice_PR_reserved83,
	mcm_CauseCodeChoice_PR_reserved84,
	mcm_CauseCodeChoice_PR_reserved85,
	mcm_CauseCodeChoice_PR_reserved86,
	mcm_CauseCodeChoice_PR_reserved87,
	mcm_CauseCodeChoice_PR_reserved88,
	mcm_CauseCodeChoice_PR_reserved89,
	mcm_CauseCodeChoice_PR_reserved90,
	mcm_CauseCodeChoice_PR_vehicleBreakdown91,
	mcm_CauseCodeChoice_PR_postCrash92,
	mcm_CauseCodeChoice_PR_humanProblem93,
	mcm_CauseCodeChoice_PR_stationaryVehicle94,
	mcm_CauseCodeChoice_PR_emergencyVehicleApproaching95,
	mcm_CauseCodeChoice_PR_hazardousLocation_DangerousCurve96,
	mcm_CauseCodeChoice_PR_collisionRisk97,
	mcm_CauseCodeChoice_PR_signalViolation98,
	mcm_CauseCodeChoice_PR_dangerousSituation99,
	mcm_CauseCodeChoice_PR_railwayLevelCrossing100,
	mcm_CauseCodeChoice_PR_reserved101,
	mcm_CauseCodeChoice_PR_reserved102,
	mcm_CauseCodeChoice_PR_reserved103,
	mcm_CauseCodeChoice_PR_reserved104,
	mcm_CauseCodeChoice_PR_reserved105,
	mcm_CauseCodeChoice_PR_reserved106,
	mcm_CauseCodeChoice_PR_reserved107,
	mcm_CauseCodeChoice_PR_reserved108,
	mcm_CauseCodeChoice_PR_reserved109,
	mcm_CauseCodeChoice_PR_reserved110,
	mcm_CauseCodeChoice_PR_reserved111,
	mcm_CauseCodeChoice_PR_reserved112,
	mcm_CauseCodeChoice_PR_reserved113,
	mcm_CauseCodeChoice_PR_reserved114,
	mcm_CauseCodeChoice_PR_reserved115,
	mcm_CauseCodeChoice_PR_reserved116,
	mcm_CauseCodeChoice_PR_reserved117,
	mcm_CauseCodeChoice_PR_reserved118,
	mcm_CauseCodeChoice_PR_reserved119,
	mcm_CauseCodeChoice_PR_reserved120,
	mcm_CauseCodeChoice_PR_reserved121,
	mcm_CauseCodeChoice_PR_reserved122,
	mcm_CauseCodeChoice_PR_reserved123,
	mcm_CauseCodeChoice_PR_reserved124,
	mcm_CauseCodeChoice_PR_reserved125,
	mcm_CauseCodeChoice_PR_reserved126,
	mcm_CauseCodeChoice_PR_reserved127,
	mcm_CauseCodeChoice_PR_reserved128
} mcm_CauseCodeChoice_PR;

/* mcm_CauseCodeChoice */
typedef struct mcm_CauseCodeChoice {
	mcm_CauseCodeChoice_PR present;
	union mcm_CauseCodeChoice_u {
		mcm_SubCauseCodeType_t	 reserved0;
		mcm_TrafficConditionSubCauseCode_t	 trafficCondition1;
		mcm_AccidentSubCauseCode_t	 accident2;
		mcm_RoadworksSubCauseCode_t	 roadworks3;
		mcm_SubCauseCodeType_t	 reserved4;
		mcm_ImpassabilitySubCauseCode_t	 impassability5;
		mcm_AdverseWeatherCondition_AdhesionSubCauseCode_t	 adverseWeatherCondition_Adhesion6;
		mcm_SubCauseCodeType_t	 aquaplaning7;
		mcm_SubCauseCodeType_t	 reserved8;
		mcm_HazardousLocation_SurfaceConditionSubCauseCode_t	 hazardousLocation_SurfaceCondition9;
		mcm_HazardousLocation_ObstacleOnTheRoadSubCauseCode_t	 hazardousLocation_ObstacleOnTheRoad10;
		mcm_HazardousLocation_AnimalOnTheRoadSubCauseCode_t	 hazardousLocation_AnimalOnTheRoad11;
		mcm_HumanPresenceOnTheRoadSubCauseCode_t	 humanPresenceOnTheRoad12;
		mcm_SubCauseCodeType_t	 reserved13;
		mcm_WrongWayDrivingSubCauseCode_t	 wrongWayDriving14;
		mcm_RescueAndRecoveryWorkInProgressSubCauseCode_t	 rescueAndRecoveryWorkInProgress15;
		mcm_SubCauseCodeType_t	 reserved16;
		mcm_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_t	 adverseWeatherCondition_ExtremeWeatherCondition17;
		mcm_AdverseWeatherCondition_VisibilitySubCauseCode_t	 adverseWeatherCondition_Visibility18;
		mcm_AdverseWeatherCondition_PrecipitationSubCauseCode_t	 adverseWeatherCondition_Precipitation19;
		mcm_SubCauseCodeType_t	 violence20;
		mcm_SubCauseCodeType_t	 reserved21;
		mcm_SubCauseCodeType_t	 reserved22;
		mcm_SubCauseCodeType_t	 reserved23;
		mcm_SubCauseCodeType_t	 reserved24;
		mcm_SubCauseCodeType_t	 reserved25;
		mcm_SlowVehicleSubCauseCode_t	 slowVehicle26;
		mcm_DangerousEndOfQueueSubCauseCode_t	 dangerousEndOfQueue27;
		mcm_SubCauseCodeType_t	 publicTransportVehicleApproaching28;
		mcm_SubCauseCodeType_t	 reserved29;
		mcm_SubCauseCodeType_t	 reserved30;
		mcm_SubCauseCodeType_t	 reserved31;
		mcm_SubCauseCodeType_t	 reserved32;
		mcm_SubCauseCodeType_t	 reserved33;
		mcm_SubCauseCodeType_t	 reserved34;
		mcm_SubCauseCodeType_t	 reserved35;
		mcm_SubCauseCodeType_t	 reserved36;
		mcm_SubCauseCodeType_t	 reserved37;
		mcm_SubCauseCodeType_t	 reserved38;
		mcm_SubCauseCodeType_t	 reserved39;
		mcm_SubCauseCodeType_t	 reserved40;
		mcm_SubCauseCodeType_t	 reserved41;
		mcm_SubCauseCodeType_t	 dontPanic42;
		mcm_SubCauseCodeType_t	 reserved43;
		mcm_SubCauseCodeType_t	 reserved44;
		mcm_SubCauseCodeType_t	 reserved45;
		mcm_SubCauseCodeType_t	 reserved46;
		mcm_SubCauseCodeType_t	 reserved47;
		mcm_SubCauseCodeType_t	 reserved48;
		mcm_SubCauseCodeType_t	 reserved49;
		mcm_SubCauseCodeType_t	 reserved50;
		mcm_SubCauseCodeType_t	 reserved51;
		mcm_SubCauseCodeType_t	 reserved52;
		mcm_SubCauseCodeType_t	 reserved53;
		mcm_SubCauseCodeType_t	 reserved54;
		mcm_SubCauseCodeType_t	 reserved55;
		mcm_SubCauseCodeType_t	 reserved56;
		mcm_SubCauseCodeType_t	 reserved57;
		mcm_SubCauseCodeType_t	 reserved58;
		mcm_SubCauseCodeType_t	 reserved59;
		mcm_SubCauseCodeType_t	 reserved60;
		mcm_SubCauseCodeType_t	 reserved61;
		mcm_SubCauseCodeType_t	 reserved62;
		mcm_SubCauseCodeType_t	 reserved63;
		mcm_SubCauseCodeType_t	 reserved64;
		mcm_SubCauseCodeType_t	 reserved65;
		mcm_SubCauseCodeType_t	 reserved66;
		mcm_SubCauseCodeType_t	 reserved67;
		mcm_SubCauseCodeType_t	 reserved68;
		mcm_SubCauseCodeType_t	 reserved69;
		mcm_SubCauseCodeType_t	 reserved70;
		mcm_SubCauseCodeType_t	 reserved71;
		mcm_SubCauseCodeType_t	 reserved72;
		mcm_SubCauseCodeType_t	 reserved73;
		mcm_SubCauseCodeType_t	 reserved74;
		mcm_SubCauseCodeType_t	 reserved75;
		mcm_SubCauseCodeType_t	 reserved76;
		mcm_SubCauseCodeType_t	 reserved77;
		mcm_SubCauseCodeType_t	 reserved78;
		mcm_SubCauseCodeType_t	 reserved79;
		mcm_SubCauseCodeType_t	 reserved80;
		mcm_SubCauseCodeType_t	 reserved81;
		mcm_SubCauseCodeType_t	 reserved82;
		mcm_SubCauseCodeType_t	 reserved83;
		mcm_SubCauseCodeType_t	 reserved84;
		mcm_SubCauseCodeType_t	 reserved85;
		mcm_SubCauseCodeType_t	 reserved86;
		mcm_SubCauseCodeType_t	 reserved87;
		mcm_SubCauseCodeType_t	 reserved88;
		mcm_SubCauseCodeType_t	 reserved89;
		mcm_SubCauseCodeType_t	 reserved90;
		mcm_VehicleBreakdownSubCauseCode_t	 vehicleBreakdown91;
		mcm_PostCrashSubCauseCode_t	 postCrash92;
		mcm_HumanProblemSubCauseCode_t	 humanProblem93;
		mcm_StationaryVehicleSubCauseCode_t	 stationaryVehicle94;
		mcm_EmergencyVehicleApproachingSubCauseCode_t	 emergencyVehicleApproaching95;
		mcm_HazardousLocation_DangerousCurveSubCauseCode_t	 hazardousLocation_DangerousCurve96;
		mcm_CollisionRiskSubCauseCode_t	 collisionRisk97;
		mcm_SignalViolationSubCauseCode_t	 signalViolation98;
		mcm_DangerousSituationSubCauseCode_t	 dangerousSituation99;
		mcm_RailwayLevelCrossingSubCauseCode_t	 railwayLevelCrossing100;
		mcm_SubCauseCodeType_t	 reserved101;
		mcm_SubCauseCodeType_t	 reserved102;
		mcm_SubCauseCodeType_t	 reserved103;
		mcm_SubCauseCodeType_t	 reserved104;
		mcm_SubCauseCodeType_t	 reserved105;
		mcm_SubCauseCodeType_t	 reserved106;
		mcm_SubCauseCodeType_t	 reserved107;
		mcm_SubCauseCodeType_t	 reserved108;
		mcm_SubCauseCodeType_t	 reserved109;
		mcm_SubCauseCodeType_t	 reserved110;
		mcm_SubCauseCodeType_t	 reserved111;
		mcm_SubCauseCodeType_t	 reserved112;
		mcm_SubCauseCodeType_t	 reserved113;
		mcm_SubCauseCodeType_t	 reserved114;
		mcm_SubCauseCodeType_t	 reserved115;
		mcm_SubCauseCodeType_t	 reserved116;
		mcm_SubCauseCodeType_t	 reserved117;
		mcm_SubCauseCodeType_t	 reserved118;
		mcm_SubCauseCodeType_t	 reserved119;
		mcm_SubCauseCodeType_t	 reserved120;
		mcm_SubCauseCodeType_t	 reserved121;
		mcm_SubCauseCodeType_t	 reserved122;
		mcm_SubCauseCodeType_t	 reserved123;
		mcm_SubCauseCodeType_t	 reserved124;
		mcm_SubCauseCodeType_t	 reserved125;
		mcm_SubCauseCodeType_t	 reserved126;
		mcm_SubCauseCodeType_t	 reserved127;
		mcm_SubCauseCodeType_t	 reserved128;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_CauseCodeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_CauseCodeChoice;
extern asn_CHOICE_specifics_t asn_SPC_mcm_CauseCodeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_CauseCodeChoice_1[129];
extern asn_per_constraints_t asn_PER_type_mcm_CauseCodeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_CauseCodeChoice_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
