/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_TrafficDirection_H_
#define	_mcm_TrafficDirection_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_TrafficDirection {
	mcm_TrafficDirection_allTrafficDirections	= 0,
	mcm_TrafficDirection_sameAsReferenceDirection_upstreamOfReferencePosition	= 1,
	mcm_TrafficDirection_sameAsReferenceDirection_downstreamOfReferencePosition	= 2,
	mcm_TrafficDirection_oppositeToReferenceDirection	= 3
} e_mcm_TrafficDirection;

/* mcm_TrafficDirection */
typedef long	 mcm_TrafficDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_TrafficDirection;
asn_struct_free_f mcm_TrafficDirection_free;
asn_struct_print_f mcm_TrafficDirection_print;
asn_constr_check_f mcm_TrafficDirection_constraint;
jer_type_encoder_f mcm_TrafficDirection_encode_jer;
per_type_decoder_f mcm_TrafficDirection_decode_uper;
per_type_encoder_f mcm_TrafficDirection_encode_uper;
per_type_decoder_f mcm_TrafficDirection_decode_aper;
per_type_encoder_f mcm_TrafficDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_TrafficDirection_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
