/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_LanePositionOptions_H_
#define	_mcm_LanePositionOptions_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_LanePosition.h"
#include "etsi_its_mcm_coding/mcm_LaneType.h"
#include "etsi_its_mcm_coding/mcm_LanePositionAndType.h"
#include "etsi_its_mcm_coding/mcm_LanePositionWithLateralDetails.h"
#include "etsi_its_mcm_coding/mcm_TrafficIslandPosition.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_LanePositionOptions_PR {
	mcm_LanePositionOptions_PR_NOTHING,	/* No components present */
	mcm_LanePositionOptions_PR_simplelanePosition,
	mcm_LanePositionOptions_PR_simpleLaneType,
	mcm_LanePositionOptions_PR_detailedlanePosition,
	mcm_LanePositionOptions_PR_lanePositionWithLateralDetails,
	mcm_LanePositionOptions_PR_trafficIslandPosition
	/* Extensions may appear below */
	
} mcm_LanePositionOptions_PR;

/* mcm_LanePositionOptions */
typedef struct mcm_LanePositionOptions {
	mcm_LanePositionOptions_PR present;
	union mcm_LanePositionOptions_u {
		mcm_LanePosition_t	 simplelanePosition;
		mcm_LaneType_t	 simpleLaneType;
		mcm_LanePositionAndType_t	 detailedlanePosition;
		mcm_LanePositionWithLateralDetails_t	 lanePositionWithLateralDetails;
		mcm_TrafficIslandPosition_t	 trafficIslandPosition;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_LanePositionOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_LanePositionOptions;
extern asn_CHOICE_specifics_t asn_SPC_mcm_LanePositionOptions_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_LanePositionOptions_1[5];
extern asn_per_constraints_t asn_PER_type_mcm_LanePositionOptions_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_LanePositionOptions_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
