/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_EmergencyPriority_H_
#define	_mcm_EmergencyPriority_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_EmergencyPriority {
	mcm_EmergencyPriority_requestForRightOfWay	= 0,
	mcm_EmergencyPriority_requestForFreeCrossingAtATrafficLight	= 1
} e_mcm_EmergencyPriority;

/* mcm_EmergencyPriority */
typedef BIT_STRING_t	 mcm_EmergencyPriority_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_EmergencyPriority;
asn_struct_free_f mcm_EmergencyPriority_free;
asn_struct_print_f mcm_EmergencyPriority_print;
asn_constr_check_f mcm_EmergencyPriority_constraint;
jer_type_encoder_f mcm_EmergencyPriority_encode_jer;
per_type_decoder_f mcm_EmergencyPriority_decode_uper;
per_type_encoder_f mcm_EmergencyPriority_encode_uper;
per_type_decoder_f mcm_EmergencyPriority_decode_aper;
per_type_encoder_f mcm_EmergencyPriority_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_EmergencyPriority_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
