/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ManoeuvreAdvice_H_
#define	_mcm_ManoeuvreAdvice_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_StationId.h"
#include "etsi_its_mcm_coding/mcm_CurrentStateAdvisedChange.h"
#include "etsi_its_mcm_coding/mcm_Submanoeuvres.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ManoeuvreAdvice */
typedef struct mcm_ManoeuvreAdvice {
	mcm_StationId_t	 executantID;
	mcm_CurrentStateAdvisedChange_t	 currentStateAdvisedChange;
	mcm_Submanoeuvres_t	 submaneuvres;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ManoeuvreAdvice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ManoeuvreAdvice;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_ManoeuvreAdvice_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ManoeuvreAdvice_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ManoeuvreAdvice_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
