/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_SlowVehicleSubCauseCode_H_
#define	_mcm_SlowVehicleSubCauseCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_SlowVehicleSubCauseCode {
	mcm_SlowVehicleSubCauseCode_unavailable	= 0,
	mcm_SlowVehicleSubCauseCode_maintenanceVehicle	= 1,
	mcm_SlowVehicleSubCauseCode_vehiclesSlowingToLookAtAccident	= 2,
	mcm_SlowVehicleSubCauseCode_abnormalLoad	= 3,
	mcm_SlowVehicleSubCauseCode_abnormalWideLoad	= 4,
	mcm_SlowVehicleSubCauseCode_convoy	= 5,
	mcm_SlowVehicleSubCauseCode_snowplough	= 6,
	mcm_SlowVehicleSubCauseCode_deicing	= 7,
	mcm_SlowVehicleSubCauseCode_saltingVehicles	= 8
} e_mcm_SlowVehicleSubCauseCode;

/* mcm_SlowVehicleSubCauseCode */
typedef long	 mcm_SlowVehicleSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_SlowVehicleSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_SlowVehicleSubCauseCode;
asn_struct_free_f mcm_SlowVehicleSubCauseCode_free;
asn_struct_print_f mcm_SlowVehicleSubCauseCode_print;
asn_constr_check_f mcm_SlowVehicleSubCauseCode_constraint;
jer_type_encoder_f mcm_SlowVehicleSubCauseCode_encode_jer;
per_type_decoder_f mcm_SlowVehicleSubCauseCode_decode_uper;
per_type_encoder_f mcm_SlowVehicleSubCauseCode_encode_uper;
per_type_decoder_f mcm_SlowVehicleSubCauseCode_decode_aper;
per_type_encoder_f mcm_SlowVehicleSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_SlowVehicleSubCauseCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
