/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ReferencePosition_H_
#define	_mcm_ReferencePosition_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Latitude.h"
#include "etsi_its_mcm_coding/mcm_Longitude.h"
#include "etsi_its_mcm_coding/mcm_PosConfidenceEllipse.h"
#include "etsi_its_mcm_coding/mcm_Altitude.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ReferencePosition */
typedef struct mcm_ReferencePosition {
	mcm_Latitude_t	 latitude;
	mcm_Longitude_t	 longitude;
	mcm_PosConfidenceEllipse_t	 positionConfidenceEllipse;
	mcm_Altitude_t	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_ReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ReferencePosition_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ReferencePosition_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
