/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PathPointPredicted_H_
#define	_mcm_PathPointPredicted_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_DeltaLatitude.h"
#include "etsi_its_mcm_coding/mcm_DeltaLongitude.h"
#include "etsi_its_mcm_coding/mcm_DeltaAltitude.h"
#include "etsi_its_mcm_coding/mcm_AltitudeConfidence.h"
#include "etsi_its_mcm_coding/mcm_StandardLength9b.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_PosConfidenceEllipse;
struct mcm_PathDeltaTimeChoice;

/* mcm_PathPointPredicted */
typedef struct mcm_PathPointPredicted {
	mcm_DeltaLatitude_t	 deltaLatitude;
	mcm_DeltaLongitude_t	 deltaLongitude;
	struct mcm_PosConfidenceEllipse	*horizontalPositionConfidence;	/* OPTIONAL */
	mcm_DeltaAltitude_t	*deltaAltitude;	/* DEFAULT 12800 */
	mcm_AltitudeConfidence_t	*altitudeConfidence;	/* DEFAULT 15 */
	struct mcm_PathDeltaTimeChoice	*pathDeltaTime;	/* OPTIONAL */
	mcm_StandardLength9b_t	*symmetricAreaOffset;	/* OPTIONAL */
	mcm_StandardLength9b_t	*asymmetricAreaOffset;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_PathPointPredicted_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_PathPointPredicted;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_PathPointPredicted_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_PathPointPredicted_1[8];
extern asn_per_constraints_t asn_PER_type_mcm_PathPointPredicted_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_PosConfidenceEllipse.h"
#include "etsi_its_mcm_coding/mcm_PathDeltaTimeChoice.h"

#endif	/* _mcm_PathPointPredicted_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
