/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_SensorTypes_H_
#define	_mcm_SensorTypes_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_SensorTypes {
	mcm_SensorTypes_undefined	= 0,
	mcm_SensorTypes_radar	= 1,
	mcm_SensorTypes_lidar	= 2,
	mcm_SensorTypes_monovideo	= 3,
	mcm_SensorTypes_stereovision	= 4,
	mcm_SensorTypes_nightvision	= 5,
	mcm_SensorTypes_ultrasonic	= 6,
	mcm_SensorTypes_pmd	= 7,
	mcm_SensorTypes_inductionLoop	= 8,
	mcm_SensorTypes_sphericalCamera	= 9,
	mcm_SensorTypes_uwb	= 10,
	mcm_SensorTypes_acoustic	= 11,
	mcm_SensorTypes_localAggregation	= 12,
	mcm_SensorTypes_itsAggregation	= 13,
	mcm_SensorTypes_rfid	= 14
} e_mcm_SensorTypes;

/* mcm_SensorTypes */
typedef BIT_STRING_t	 mcm_SensorTypes_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_SensorTypes_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_SensorTypes;
asn_struct_free_f mcm_SensorTypes_free;
asn_struct_print_f mcm_SensorTypes_print;
asn_constr_check_f mcm_SensorTypes_constraint;
jer_type_encoder_f mcm_SensorTypes_encode_jer;
per_type_decoder_f mcm_SensorTypes_decode_uper;
per_type_encoder_f mcm_SensorTypes_encode_uper;
per_type_decoder_f mcm_SensorTypes_decode_aper;
per_type_encoder_f mcm_SensorTypes_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_SensorTypes_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
