/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_TrailerData_H_
#define	_mcm_TrailerData_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier1B.h"
#include "etsi_its_mcm_coding/mcm_StandardLength1B.h"
#include "etsi_its_mcm_coding/mcm_VehicleWidth.h"
#include "etsi_its_mcm_coding/mcm_CartesianAngle.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_TrailerData */
typedef struct mcm_TrailerData {
	mcm_Identifier1B_t	 refPointId;
	mcm_StandardLength1B_t	 hitchPointOffset;
	mcm_StandardLength1B_t	*frontOverhang;	/* OPTIONAL */
	mcm_StandardLength1B_t	*rearOverhang;	/* OPTIONAL */
	mcm_VehicleWidth_t	*trailerWidth;	/* OPTIONAL */
	mcm_CartesianAngle_t	 hitchAngle;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_TrailerData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_TrailerData;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_TrailerData_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
