/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_McmContainer_H_
#define	_mcm_McmContainer_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_VehicleManoeuvreContainer.h"
#include "etsi_its_mcm_coding/mcm_ManoeuvreAdviceContainer.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_McmContainer_PR {
	mcm_McmContainer_PR_NOTHING,	/* No components present */
	mcm_McmContainer_PR_vehicleManoeuvreContainer,
	mcm_McmContainer_PR_advisedManoeuvreContainer
} mcm_McmContainer_PR;

/* mcm_McmContainer */
typedef struct mcm_McmContainer {
	mcm_McmContainer_PR present;
	union mcm_McmContainer_u {
		mcm_VehicleManoeuvreContainer_t	 vehicleManoeuvreContainer;
		mcm_ManoeuvreAdviceContainer_t	 advisedManoeuvreContainer;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_McmContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_McmContainer;
extern asn_CHOICE_specifics_t asn_SPC_mcm_McmContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_McmContainer_1[2];
extern asn_per_constraints_t asn_PER_type_mcm_McmContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_McmContainer_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
