/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_MatrixIncludedComponents_H_
#define	_mcm_MatrixIncludedComponents_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_MatrixIncludedComponents {
	mcm_MatrixIncludedComponents_xPosition	= 0,
	mcm_MatrixIncludedComponents_yPosition	= 1,
	mcm_MatrixIncludedComponents_zPosition	= 2,
	mcm_MatrixIncludedComponents_xVelocityOrVelocityMagnitude	= 3,
	mcm_MatrixIncludedComponents_yVelocityOrVelocityDirection	= 4,
	mcm_MatrixIncludedComponents_zSpeed	= 5,
	mcm_MatrixIncludedComponents_xAccelOrAccelMagnitude	= 6,
	mcm_MatrixIncludedComponents_yAccelOrAccelDirection	= 7,
	mcm_MatrixIncludedComponents_zAcceleration	= 8,
	mcm_MatrixIncludedComponents_zAngle	= 9,
	mcm_MatrixIncludedComponents_yAngle	= 10,
	mcm_MatrixIncludedComponents_xAngle	= 11,
	mcm_MatrixIncludedComponents_zAngularVelocity	= 12
} e_mcm_MatrixIncludedComponents;

/* mcm_MatrixIncludedComponents */
typedef BIT_STRING_t	 mcm_MatrixIncludedComponents_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_MatrixIncludedComponents_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_MatrixIncludedComponents;
asn_struct_free_f mcm_MatrixIncludedComponents_free;
asn_struct_print_f mcm_MatrixIncludedComponents_print;
asn_constr_check_f mcm_MatrixIncludedComponents_constraint;
jer_type_encoder_f mcm_MatrixIncludedComponents_encode_jer;
per_type_decoder_f mcm_MatrixIncludedComponents_decode_uper;
per_type_encoder_f mcm_MatrixIncludedComponents_encode_uper;
per_type_decoder_f mcm_MatrixIncludedComponents_decode_aper;
per_type_encoder_f mcm_MatrixIncludedComponents_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_MatrixIncludedComponents_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
