/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_McmItssRole_H_
#define	_mcm_McmItssRole_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_McmItssRole {
	mcm_McmItssRole_notAvailable	= 0,
	mcm_McmItssRole_coordinatingItss	= 1,
	mcm_McmItssRole_notCoordinatingSubjectVehicle	= 2,
	mcm_McmItssRole_targetVehicle	= 3
	/*
	 * Enumeration is extensible
	 */
} e_mcm_McmItssRole;

/* mcm_McmItssRole */
typedef long	 mcm_McmItssRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_McmItssRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_McmItssRole;
extern const asn_INTEGER_specifics_t asn_SPC_mcm_McmItssRole_specs_1;
asn_struct_free_f mcm_McmItssRole_free;
asn_struct_print_f mcm_McmItssRole_print;
asn_constr_check_f mcm_McmItssRole_constraint;
jer_type_encoder_f mcm_McmItssRole_encode_jer;
per_type_decoder_f mcm_McmItssRole_decode_uper;
per_type_encoder_f mcm_McmItssRole_encode_uper;
per_type_decoder_f mcm_McmItssRole_decode_aper;
per_type_encoder_f mcm_McmItssRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_McmItssRole_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
