/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VruProfileAndSubprofile_H_
#define	_mcm_VruProfileAndSubprofile_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_VruSubProfilePedestrian.h"
#include "etsi_its_mcm_coding/mcm_VruSubProfileBicyclist.h"
#include "etsi_its_mcm_coding/mcm_VruSubProfileMotorcyclist.h"
#include "etsi_its_mcm_coding/mcm_VruSubProfileAnimal.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_VruProfileAndSubprofile_PR {
	mcm_VruProfileAndSubprofile_PR_NOTHING,	/* No components present */
	mcm_VruProfileAndSubprofile_PR_pedestrian,
	mcm_VruProfileAndSubprofile_PR_bicyclistAndLightVruVehicle,
	mcm_VruProfileAndSubprofile_PR_motorcyclist,
	mcm_VruProfileAndSubprofile_PR_animal
	/* Extensions may appear below */
	
} mcm_VruProfileAndSubprofile_PR;

/* mcm_VruProfileAndSubprofile */
typedef struct mcm_VruProfileAndSubprofile {
	mcm_VruProfileAndSubprofile_PR present;
	union mcm_VruProfileAndSubprofile_u {
		mcm_VruSubProfilePedestrian_t	 pedestrian;
		mcm_VruSubProfileBicyclist_t	 bicyclistAndLightVruVehicle;
		mcm_VruSubProfileMotorcyclist_t	 motorcyclist;
		mcm_VruSubProfileAnimal_t	 animal;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_VruProfileAndSubprofile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VruProfileAndSubprofile;
extern asn_CHOICE_specifics_t asn_SPC_mcm_VruProfileAndSubprofile_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_VruProfileAndSubprofile_1[4];
extern asn_per_constraints_t asn_PER_type_mcm_VruProfileAndSubprofile_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_VruProfileAndSubprofile_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
