/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_InterferenceManagementInfoPerChannel_H_
#define	_mcm_InterferenceManagementInfoPerChannel_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_InterferenceManagementChannel.h"
#include "etsi_its_mcm_coding/mcm_InterferenceManagementZoneType.h"
#include "etsi_its_mcm_coding/mcm_TimestampIts.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_MitigationForTechnologies;

/* mcm_InterferenceManagementInfoPerChannel */
typedef struct mcm_InterferenceManagementInfoPerChannel {
	mcm_InterferenceManagementChannel_t	 interferenceManagementChannel;
	mcm_InterferenceManagementZoneType_t	 interferenceManagementZoneType;
	struct mcm_MitigationForTechnologies	*interferenceManagementMitigationType;	/* OPTIONAL */
	mcm_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_InterferenceManagementInfoPerChannel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_InterferenceManagementInfoPerChannel;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_InterferenceManagementInfoPerChannel_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_InterferenceManagementInfoPerChannel_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_MitigationForTechnologies.h"

#endif	/* _mcm_InterferenceManagementInfoPerChannel_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
