/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VerticalAcceleration_H_
#define	_mcm_VerticalAcceleration_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_VerticalAccelerationValue.h"
#include "etsi_its_mcm_coding/mcm_AccelerationConfidence.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_VerticalAcceleration */
typedef struct mcm_VerticalAcceleration {
	mcm_VerticalAccelerationValue_t	 verticalAccelerationValue;
	mcm_AccelerationConfidence_t	 verticalAccelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_VerticalAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VerticalAcceleration;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_VerticalAcceleration_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
