/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PhoneNumber_H_
#define	_mcm_PhoneNumber_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_PhoneNumber */
typedef NumericString_t	 mcm_PhoneNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_PhoneNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_PhoneNumber;
asn_struct_free_f mcm_PhoneNumber_free;
asn_struct_print_f mcm_PhoneNumber_print;
asn_constr_check_f mcm_PhoneNumber_constraint;
jer_type_encoder_f mcm_PhoneNumber_encode_jer;
per_type_decoder_f mcm_PhoneNumber_decode_uper;
per_type_encoder_f mcm_PhoneNumber_encode_uper;
per_type_decoder_f mcm_PhoneNumber_decode_aper;
per_type_encoder_f mcm_PhoneNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_PhoneNumber_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
