/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_UsageIndication_H_
#define	_mcm_UsageIndication_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_UsageIndication {
	mcm_UsageIndication_noIndication	= 0,
	mcm_UsageIndication_specialUse	= 1,
	mcm_UsageIndication_rescueOperation	= 2,
	/*
	 * Enumeration is extensible
	 */
	mcm_UsageIndication_railroad	= 3,
	mcm_UsageIndication_fixedRoute	= 4,
	mcm_UsageIndication_restrictedRoute	= 5,
	mcm_UsageIndication_adasAd	= 6,
	mcm_UsageIndication_navigation	= 7
} e_mcm_UsageIndication;

/* mcm_UsageIndication */
typedef long	 mcm_UsageIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_UsageIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_UsageIndication;
extern const asn_INTEGER_specifics_t asn_SPC_mcm_UsageIndication_specs_1;
asn_struct_free_f mcm_UsageIndication_free;
asn_struct_print_f mcm_UsageIndication_print;
asn_constr_check_f mcm_UsageIndication_constraint;
jer_type_encoder_f mcm_UsageIndication_encode_jer;
per_type_decoder_f mcm_UsageIndication_decode_uper;
per_type_encoder_f mcm_UsageIndication_encode_uper;
per_type_decoder_f mcm_UsageIndication_decode_aper;
per_type_encoder_f mcm_UsageIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_UsageIndication_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
