/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_IvimReferences_H_
#define	_mcm_IvimReferences_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_IvimReference;

/* mcm_IvimReferences */
typedef struct mcm_IvimReferences {
	A_SEQUENCE_OF(struct mcm_IvimReference) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_IvimReferences_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_IvimReferences;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_IvimReference.h"

#endif	/* _mcm_IvimReferences_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
