/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PerceivedObject_H_
#define	_mcm_PerceivedObject_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier2B.h"
#include "etsi_its_mcm_coding/mcm_DeltaTimeMilliSecondSigned.h"
#include "etsi_its_mcm_coding/mcm_CartesianPosition3dWithConfidence.h"
#include "etsi_its_mcm_coding/mcm_ObjectPerceptionQuality.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_Velocity3dWithConfidence;
struct mcm_Acceleration3dWithConfidence;
struct mcm_EulerAnglesWithConfidence;
struct mcm_CartesianAngularVelocityComponent;
struct mcm_LowerTriangularPositiveSemidefiniteMatrices;
struct mcm_ObjectDimension;
struct mcm_SequenceOfIdentifier1B;
struct mcm_ObjectClassDescription;
struct mcm_MapPosition;

/* mcm_PerceivedObject */
typedef struct mcm_PerceivedObject {
	mcm_Identifier2B_t	*objectId;	/* OPTIONAL */
	mcm_DeltaTimeMilliSecondSigned_t	 measurementDeltaTime;
	mcm_CartesianPosition3dWithConfidence_t	 position;
	struct mcm_Velocity3dWithConfidence	*velocity;	/* OPTIONAL */
	struct mcm_Acceleration3dWithConfidence	*acceleration;	/* OPTIONAL */
	struct mcm_EulerAnglesWithConfidence	*angles;	/* OPTIONAL */
	struct mcm_CartesianAngularVelocityComponent	*zAngularVelocity;	/* OPTIONAL */
	struct mcm_LowerTriangularPositiveSemidefiniteMatrices	*lowerTriangularCorrelationMatrices;	/* OPTIONAL */
	struct mcm_ObjectDimension	*objectDimensionZ;	/* OPTIONAL */
	struct mcm_ObjectDimension	*objectDimensionY;	/* OPTIONAL */
	struct mcm_ObjectDimension	*objectDimensionX;	/* OPTIONAL */
	mcm_DeltaTimeMilliSecondSigned_t	*objectAge;	/* OPTIONAL */
	mcm_ObjectPerceptionQuality_t	*objectPerceptionQuality;	/* OPTIONAL */
	struct mcm_SequenceOfIdentifier1B	*sensorIdList;	/* OPTIONAL */
	struct mcm_ObjectClassDescription	*classification;	/* OPTIONAL */
	struct mcm_MapPosition	*mapPosition;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_PerceivedObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_PerceivedObject;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_Velocity3dWithConfidence.h"
#include "etsi_its_mcm_coding/mcm_Acceleration3dWithConfidence.h"
#include "etsi_its_mcm_coding/mcm_EulerAnglesWithConfidence.h"
#include "etsi_its_mcm_coding/mcm_CartesianAngularVelocityComponent.h"
#include "etsi_its_mcm_coding/mcm_LowerTriangularPositiveSemidefiniteMatrices.h"
#include "etsi_its_mcm_coding/mcm_ObjectDimension.h"
#include "etsi_its_mcm_coding/mcm_SequenceOfIdentifier1B.h"
#include "etsi_its_mcm_coding/mcm_ObjectClassDescription.h"
#include "etsi_its_mcm_coding/mcm_MapPosition.h"

#endif	/* _mcm_PerceivedObject_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
