/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_CartesianPosition3dWithConfidence_H_
#define	_mcm_CartesianPosition3dWithConfidence_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_CartesianCoordinateWithConfidence.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_CartesianCoordinateWithConfidence;

/* mcm_CartesianPosition3dWithConfidence */
typedef struct mcm_CartesianPosition3dWithConfidence {
	mcm_CartesianCoordinateWithConfidence_t	 xCoordinate;
	mcm_CartesianCoordinateWithConfidence_t	 yCoordinate;
	struct mcm_CartesianCoordinateWithConfidence	*zCoordinate;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_CartesianPosition3dWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_CartesianPosition3dWithConfidence;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_CartesianPosition3dWithConfidence_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_CartesianPosition3dWithConfidence_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_CartesianCoordinateWithConfidence.h"

#endif	/* _mcm_CartesianPosition3dWithConfidence_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
