/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VehicleIdentification_H_
#define	_mcm_VehicleIdentification_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_WMInumber.h"
#include "etsi_its_mcm_coding/mcm_VDS.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_VehicleIdentification */
typedef struct mcm_VehicleIdentification {
	mcm_WMInumber_t	*wMInumber;	/* OPTIONAL */
	mcm_VDS_t	*vDS;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_VehicleIdentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VehicleIdentification;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_VehicleIdentification_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
