/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_RLLC_H_
#define	_mcm_RLLC_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_RLLC {
	mcm_RLLC_currentLane	= 0
} e_mcm_RLLC;

/* mcm_RLLC */
typedef BIT_STRING_t	 mcm_RLLC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_RLLC;
asn_struct_free_f mcm_RLLC_free;
asn_struct_print_f mcm_RLLC_print;
asn_constr_check_f mcm_RLLC_constraint;
jer_type_encoder_f mcm_RLLC_encode_jer;
per_type_decoder_f mcm_RLLC_decode_uper;
per_type_encoder_f mcm_RLLC_encode_uper;
per_type_decoder_f mcm_RLLC_decode_aper;
per_type_encoder_f mcm_RLLC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_RLLC_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
