/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_HumanProblemSubCauseCode_H_
#define	_mcm_HumanProblemSubCauseCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_HumanProblemSubCauseCode {
	mcm_HumanProblemSubCauseCode_unavailable	= 0,
	mcm_HumanProblemSubCauseCode_glycemiaProblem	= 1,
	mcm_HumanProblemSubCauseCode_heartProblem	= 2
} e_mcm_HumanProblemSubCauseCode;

/* mcm_HumanProblemSubCauseCode */
typedef long	 mcm_HumanProblemSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_HumanProblemSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_HumanProblemSubCauseCode;
asn_struct_free_f mcm_HumanProblemSubCauseCode_free;
asn_struct_print_f mcm_HumanProblemSubCauseCode_print;
asn_constr_check_f mcm_HumanProblemSubCauseCode_constraint;
jer_type_encoder_f mcm_HumanProblemSubCauseCode_encode_jer;
per_type_decoder_f mcm_HumanProblemSubCauseCode_decode_uper;
per_type_encoder_f mcm_HumanProblemSubCauseCode_encode_uper;
per_type_decoder_f mcm_HumanProblemSubCauseCode_decode_aper;
per_type_encoder_f mcm_HumanProblemSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_HumanProblemSubCauseCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
