/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PosCentMass_H_
#define	_mcm_PosCentMass_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_PosCentMass {
	mcm_PosCentMass_tenCentimetres	= 1,
	mcm_PosCentMass_outOfRange	= 62,
	mcm_PosCentMass_unavailable	= 63
} e_mcm_PosCentMass;

/* mcm_PosCentMass */
typedef long	 mcm_PosCentMass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_PosCentMass;
asn_struct_free_f mcm_PosCentMass_free;
asn_struct_print_f mcm_PosCentMass_print;
asn_constr_check_f mcm_PosCentMass_constraint;
jer_type_encoder_f mcm_PosCentMass_encode_jer;
per_type_decoder_f mcm_PosCentMass_decode_uper;
per_type_encoder_f mcm_PosCentMass_encode_uper;
per_type_decoder_f mcm_PosCentMass_decode_aper;
per_type_encoder_f mcm_PosCentMass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_PosCentMass_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
