/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PolygonalShape_H_
#define	_mcm_PolygonalShape_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_SequenceOfCartesianPosition3d.h"
#include "etsi_its_mcm_coding/mcm_StandardLength12b.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_CartesianPosition3d;

/* mcm_PolygonalShape */
typedef struct mcm_PolygonalShape {
	struct mcm_CartesianPosition3d	*shapeReferencePoint;	/* OPTIONAL */
	mcm_SequenceOfCartesianPosition3d_t	 polygon;
	mcm_StandardLength12b_t	*height;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_PolygonalShape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_PolygonalShape;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_PolygonalShape_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_PolygonalShape_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_CartesianPosition3d.h"

#endif	/* _mcm_PolygonalShape_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
