/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_GeoPositionsWoAltitude_H_
#define	_mcm_GeoPositionsWoAltitude_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_GeoPositionWoAltitude;

/* mcm_GeoPositionsWoAltitude */
typedef struct mcm_GeoPositionsWoAltitude {
	A_SEQUENCE_OF(struct mcm_GeoPositionWoAltitude) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_GeoPositionsWoAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_GeoPositionsWoAltitude;
extern asn_SET_OF_specifics_t asn_SPC_mcm_GeoPositionsWoAltitude_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_GeoPositionsWoAltitude_1[1];
extern asn_per_constraints_t asn_PER_type_mcm_GeoPositionsWoAltitude_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_GeoPositionWoAltitude.h"

#endif	/* _mcm_GeoPositionsWoAltitude_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
