/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_AdvisedTrrContainer_H_
#define	_mcm_AdvisedTrrContainer_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_TrrDescription.h"
#include "etsi_its_mcm_coding/mcm_TemporalCharacteristics.h"
#include "etsi_its_mcm_coding/mcm_KinematicsCharacteristics.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_AdvisedTrrContainer */
typedef struct mcm_AdvisedTrrContainer {
	mcm_TrrDescription_t	 trrDescription;
	mcm_TemporalCharacteristics_t	 temporalCharacteristics;
	mcm_KinematicsCharacteristics_t	 kinematicsCharacteristics;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_AdvisedTrrContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_AdvisedTrrContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_AdvisedTrrContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_AdvisedTrrContainer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_AdvisedTrrContainer_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
