/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_TrafficConditionSubCauseCode_H_
#define	_mcm_TrafficConditionSubCauseCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_TrafficConditionSubCauseCode {
	mcm_TrafficConditionSubCauseCode_unavailable	= 0,
	mcm_TrafficConditionSubCauseCode_increasedVolumeOfTraffic	= 1,
	mcm_TrafficConditionSubCauseCode_trafficJamSlowlyIncreasing	= 2,
	mcm_TrafficConditionSubCauseCode_trafficJamIncreasing	= 3,
	mcm_TrafficConditionSubCauseCode_trafficJamStronglyIncreasing	= 4,
	mcm_TrafficConditionSubCauseCode_trafficJam	= 5,
	mcm_TrafficConditionSubCauseCode_trafficJamSlightlyDecreasing	= 6,
	mcm_TrafficConditionSubCauseCode_trafficJamDecreasing	= 7,
	mcm_TrafficConditionSubCauseCode_trafficJamStronglyDecreasing	= 8,
	mcm_TrafficConditionSubCauseCode_trafficJamStable	= 9
} e_mcm_TrafficConditionSubCauseCode;

/* mcm_TrafficConditionSubCauseCode */
typedef long	 mcm_TrafficConditionSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_TrafficConditionSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_TrafficConditionSubCauseCode;
asn_struct_free_f mcm_TrafficConditionSubCauseCode_free;
asn_struct_print_f mcm_TrafficConditionSubCauseCode_print;
asn_constr_check_f mcm_TrafficConditionSubCauseCode_constraint;
jer_type_encoder_f mcm_TrafficConditionSubCauseCode_encode_jer;
per_type_decoder_f mcm_TrafficConditionSubCauseCode_decode_uper;
per_type_encoder_f mcm_TrafficConditionSubCauseCode_encode_uper;
per_type_decoder_f mcm_TrafficConditionSubCauseCode_decode_aper;
per_type_encoder_f mcm_TrafficConditionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_TrafficConditionSubCauseCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
