/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ProtectedCommunicationZone_H_
#define	_mcm_ProtectedCommunicationZone_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_ProtectedZoneType.h"
#include "etsi_its_mcm_coding/mcm_TimestampIts.h"
#include "etsi_its_mcm_coding/mcm_Latitude.h"
#include "etsi_its_mcm_coding/mcm_Longitude.h"
#include "etsi_its_mcm_coding/mcm_ProtectedZoneRadius.h"
#include "etsi_its_mcm_coding/mcm_ProtectedZoneId.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ProtectedCommunicationZone */
typedef struct mcm_ProtectedCommunicationZone {
	mcm_ProtectedZoneType_t	 protectedZoneType;
	mcm_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	mcm_Latitude_t	 protectedZoneLatitude;
	mcm_Longitude_t	 protectedZoneLongitude;
	mcm_ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	mcm_ProtectedZoneId_t	*protectedZoneId;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ProtectedCommunicationZone_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
