/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_AdverseWeatherCondition_AdhesionSubCauseCode_H_
#define	_mcm_AdverseWeatherCondition_AdhesionSubCauseCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_AdverseWeatherCondition_AdhesionSubCauseCode {
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_unavailable	= 0,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_heavyFrostOnRoad	= 1,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_fuelOnRoad	= 2,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_mudOnRoad	= 3,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_snowOnRoad	= 4,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_iceOnRoad	= 5,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_blackIceOnRoad	= 6,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_oilOnRoad	= 7,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_looseChippings	= 8,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_instantBlackIce	= 9,
	mcm_AdverseWeatherCondition_AdhesionSubCauseCode_roadsSalted	= 10
} e_mcm_AdverseWeatherCondition_AdhesionSubCauseCode;

/* mcm_AdverseWeatherCondition-AdhesionSubCauseCode */
typedef long	 mcm_AdverseWeatherCondition_AdhesionSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_AdverseWeatherCondition_AdhesionSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_AdverseWeatherCondition_AdhesionSubCauseCode;
asn_struct_free_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_free;
asn_struct_print_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_print;
asn_constr_check_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_constraint;
jer_type_encoder_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_jer;
per_type_decoder_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_decode_uper;
per_type_encoder_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_uper;
per_type_decoder_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_decode_aper;
per_type_encoder_f mcm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_AdverseWeatherCondition_AdhesionSubCauseCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
