/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_RoadSectionDefinition_H_
#define	_mcm_RoadSectionDefinition_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_GeoPosition.h"
#include "etsi_its_mcm_coding/mcm_StandardLength2B.h"
#include "etsi_its_mcm_coding/mcm_PathReferences.h"
#include <etsi_its_mcm_coding/BOOLEAN.h>
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_GeoPosition;

/* mcm_RoadSectionDefinition */
typedef struct mcm_RoadSectionDefinition {
	mcm_GeoPosition_t	 startingPointSection;
	mcm_StandardLength2B_t	*lengthOfSection;	/* OPTIONAL */
	struct mcm_GeoPosition	*endingPointSection;	/* OPTIONAL */
	mcm_PathReferences_t	 connectedPaths;
	mcm_PathReferences_t	 includedPaths;
	BOOLEAN_t	 isEventZoneIncluded;
	BOOLEAN_t	 isEventZoneConnected;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_RoadSectionDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_RoadSectionDefinition;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_RoadSectionDefinition_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_RoadSectionDefinition_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_GeoPosition.h"

#endif	/* _mcm_RoadSectionDefinition_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
