/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VelocityPolarWithZ_H_
#define	_mcm_VelocityPolarWithZ_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Speed.h"
#include "etsi_its_mcm_coding/mcm_CartesianAngle.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_VelocityComponent;

/* mcm_VelocityPolarWithZ */
typedef struct mcm_VelocityPolarWithZ {
	mcm_Speed_t	 velocityMagnitude;
	mcm_CartesianAngle_t	 velocityDirection;
	struct mcm_VelocityComponent	*zVelocity;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_VelocityPolarWithZ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VelocityPolarWithZ;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_VelocityPolarWithZ_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_VelocityPolarWithZ_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_VelocityComponent.h"

#endif	/* _mcm_VelocityPolarWithZ_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
