/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_AccelerationMagnitude_H_
#define	_mcm_AccelerationMagnitude_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_AccelerationMagnitudeValue.h"
#include "etsi_its_mcm_coding/mcm_AccelerationConfidence.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_AccelerationMagnitude */
typedef struct mcm_AccelerationMagnitude {
	mcm_AccelerationMagnitudeValue_t	 accelerationMagnitudeValue;
	mcm_AccelerationConfidence_t	 accelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_AccelerationMagnitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_AccelerationMagnitude;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_AccelerationMagnitude_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_AccelerationMagnitude_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_AccelerationMagnitude_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
