/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_LanePosition_H_
#define	_mcm_LanePosition_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_LanePosition {
	mcm_LanePosition_offTheRoad	= -1,
	mcm_LanePosition_innerHardShoulder	= 0,
	mcm_LanePosition_outerHardShoulder	= 14
} e_mcm_LanePosition;

/* mcm_LanePosition */
typedef long	 mcm_LanePosition_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_LanePosition_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_LanePosition;
asn_struct_free_f mcm_LanePosition_free;
asn_struct_print_f mcm_LanePosition_print;
asn_constr_check_f mcm_LanePosition_constraint;
jer_type_encoder_f mcm_LanePosition_encode_jer;
per_type_decoder_f mcm_LanePosition_decode_uper;
per_type_encoder_f mcm_LanePosition_encode_uper;
per_type_decoder_f mcm_LanePosition_decode_aper;
per_type_encoder_f mcm_LanePosition_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_LanePosition_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
