/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ManouevreResponse_H_
#define	_mcm_ManouevreResponse_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NULL.h>
#include "etsi_its_mcm_coding/mcm_RequestDeclineReaseon.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ManouevreResponse_PR {
	mcm_ManouevreResponse_PR_NOTHING,	/* No components present */
	mcm_ManouevreResponse_PR_offerAcceptation,
	mcm_ManouevreResponse_PR_offerDecline,
	mcm_ManouevreResponse_PR_requestAcceptation,
	mcm_ManouevreResponse_PR_requestDecline
} mcm_ManouevreResponse_PR;

/* mcm_ManouevreResponse */
typedef struct mcm_ManouevreResponse {
	mcm_ManouevreResponse_PR present;
	union mcm_ManouevreResponse_u {
		NULL_t	 offerAcceptation;
		NULL_t	 offerDecline;
		NULL_t	 requestAcceptation;
		mcm_RequestDeclineReaseon_t	 requestDecline;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ManouevreResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ManouevreResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ManouevreResponse_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
