/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_CauseCodeType_H_
#define	_mcm_CauseCodeType_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_CauseCodeType {
	mcm_CauseCodeType_trafficCondition	= 1,
	mcm_CauseCodeType_accident	= 2,
	mcm_CauseCodeType_roadworks	= 3,
	mcm_CauseCodeType_impassability	= 5,
	mcm_CauseCodeType_adverseWeatherCondition_Adhesion	= 6,
	mcm_CauseCodeType_aquaplaning	= 7,
	mcm_CauseCodeType_hazardousLocation_SurfaceCondition	= 9,
	mcm_CauseCodeType_hazardousLocation_ObstacleOnTheRoad	= 10,
	mcm_CauseCodeType_hazardousLocation_AnimalOnTheRoad	= 11,
	mcm_CauseCodeType_humanPresenceOnTheRoad	= 12,
	mcm_CauseCodeType_wrongWayDriving	= 14,
	mcm_CauseCodeType_rescueAndRecoveryWorkInProgress	= 15,
	mcm_CauseCodeType_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	mcm_CauseCodeType_adverseWeatherCondition_Visibility	= 18,
	mcm_CauseCodeType_adverseWeatherCondition_Precipitation	= 19,
	mcm_CauseCodeType_violence	= 20,
	mcm_CauseCodeType_slowVehicle	= 26,
	mcm_CauseCodeType_dangerousEndOfQueue	= 27,
	mcm_CauseCodeType_publicTransportVehicleApproaching	= 28,
	mcm_CauseCodeType_vehicleBreakdown	= 91,
	mcm_CauseCodeType_postCrash	= 92,
	mcm_CauseCodeType_humanProblem	= 93,
	mcm_CauseCodeType_stationaryVehicle	= 94,
	mcm_CauseCodeType_emergencyVehicleApproaching	= 95,
	mcm_CauseCodeType_hazardousLocation_DangerousCurve	= 96,
	mcm_CauseCodeType_collisionRisk	= 97,
	mcm_CauseCodeType_signalViolation	= 98,
	mcm_CauseCodeType_dangerousSituation	= 99,
	mcm_CauseCodeType_railwayLevelCrossing	= 100
} e_mcm_CauseCodeType;

/* mcm_CauseCodeType */
typedef long	 mcm_CauseCodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_CauseCodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_CauseCodeType;
asn_struct_free_f mcm_CauseCodeType_free;
asn_struct_print_f mcm_CauseCodeType_print;
asn_constr_check_f mcm_CauseCodeType_constraint;
jer_type_encoder_f mcm_CauseCodeType_encode_jer;
per_type_decoder_f mcm_CauseCodeType_decode_uper;
per_type_encoder_f mcm_CauseCodeType_encode_uper;
per_type_decoder_f mcm_CauseCodeType_decode_aper;
per_type_encoder_f mcm_CauseCodeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_CauseCodeType_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
