/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_SubmanoeuvreStrategy_H_
#define	_mcm_SubmanoeuvreStrategy_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NULL.h>
#include <etsi_its_mcm_coding/NativeInteger.h>
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_SubmanoeuvreStrategy_PR {
	mcm_SubmanoeuvreStrategy_PR_NOTHING,	/* No components present */
	mcm_SubmanoeuvreStrategy_PR_undefined,
	mcm_SubmanoeuvreStrategy_PR_transitToHumanDrivenMode,
	mcm_SubmanoeuvreStrategy_PR_transitToAutomatedDrivingMode,
	mcm_SubmanoeuvreStrategy_PR_driveStraight,
	mcm_SubmanoeuvreStrategy_PR_turnLeft,
	mcm_SubmanoeuvreStrategy_PR_turnRight,
	mcm_SubmanoeuvreStrategy_PR_uTurn,
	mcm_SubmanoeuvreStrategy_PR_moveBackward,
	mcm_SubmanoeuvreStrategy_PR_overtake,
	mcm_SubmanoeuvreStrategy_PR_accelerate,
	mcm_SubmanoeuvreStrategy_PR_slowDown,
	mcm_SubmanoeuvreStrategy_PR_stop,
	mcm_SubmanoeuvreStrategy_PR_goToLeftLane,
	mcm_SubmanoeuvreStrategy_PR_goToRightLane,
	mcm_SubmanoeuvreStrategy_PR_getOnHighway,
	mcm_SubmanoeuvreStrategy_PR_exitHighway,
	mcm_SubmanoeuvreStrategy_PR_takeTollingLane,
	mcm_SubmanoeuvreStrategy_PR_stopAndWait,
	mcm_SubmanoeuvreStrategy_PR_emergencyBrakeAndStop,
	mcm_SubmanoeuvreStrategy_PR_resetStopAndRestartMoving,
	mcm_SubmanoeuvreStrategy_PR_stayInLane,
	mcm_SubmanoeuvreStrategy_PR_resetStayInLane,
	mcm_SubmanoeuvreStrategy_PR_stayAway,
	mcm_SubmanoeuvreStrategy_PR_resetStayAway,
	mcm_SubmanoeuvreStrategy_PR_followMe,
	mcm_SubmanoeuvreStrategy_PR_existingGroup,
	mcm_SubmanoeuvreStrategy_PR_temporarilyDisbandAnExistingGroup,
	mcm_SubmanoeuvreStrategy_PR_constituteATemporarilyGroup,
	mcm_SubmanoeuvreStrategy_PR_disbandATemporarilyGroup
} mcm_SubmanoeuvreStrategy_PR;

/* mcm_SubmanoeuvreStrategy */
typedef struct mcm_SubmanoeuvreStrategy {
	mcm_SubmanoeuvreStrategy_PR present;
	union mcm_SubmanoeuvreStrategy_u {
		NULL_t	 undefined;
		NULL_t	 transitToHumanDrivenMode;
		NULL_t	 transitToAutomatedDrivingMode;
		NULL_t	 driveStraight;
		NULL_t	 turnLeft;
		NULL_t	 turnRight;
		NULL_t	 uTurn;
		NULL_t	 moveBackward;
		NULL_t	 overtake;
		NULL_t	 accelerate;
		NULL_t	 slowDown;
		NULL_t	 stop;
		NULL_t	 goToLeftLane;
		NULL_t	 goToRightLane;
		NULL_t	 getOnHighway;
		NULL_t	 exitHighway;
		long	 takeTollingLane;
		NULL_t	 stopAndWait;
		NULL_t	 emergencyBrakeAndStop;
		NULL_t	 resetStopAndRestartMoving;
		NULL_t	 stayInLane;
		NULL_t	 resetStayInLane;
		NULL_t	 stayAway;
		NULL_t	 resetStayAway;
		NULL_t	 followMe;
		NULL_t	 existingGroup;
		NULL_t	 temporarilyDisbandAnExistingGroup;
		NULL_t	 constituteATemporarilyGroup;
		NULL_t	 disbandATemporarilyGroup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_SubmanoeuvreStrategy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_SubmanoeuvreStrategy;
extern asn_CHOICE_specifics_t asn_SPC_mcm_SubmanoeuvreStrategy_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_SubmanoeuvreStrategy_1[29];
extern asn_per_constraints_t asn_PER_type_mcm_SubmanoeuvreStrategy_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_SubmanoeuvreStrategy_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
