/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_Direction_H_
#define	_mcm_Direction_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_Direction {
	mcm_Direction_sameDirection	= 0,
	mcm_Direction_oppositeDirection	= 1,
	mcm_Direction_bothDirections	= 2,
	mcm_Direction_unavailable	= 3
} e_mcm_Direction;

/* mcm_Direction */
typedef long	 mcm_Direction_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_Direction_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_Direction;
asn_struct_free_f mcm_Direction_free;
asn_struct_print_f mcm_Direction_print;
asn_constr_check_f mcm_Direction_constraint;
jer_type_encoder_f mcm_Direction_encode_jer;
per_type_decoder_f mcm_Direction_decode_uper;
per_type_encoder_f mcm_Direction_encode_uper;
per_type_decoder_f mcm_Direction_decode_aper;
per_type_encoder_f mcm_Direction_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_Direction_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
