/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VruClusterInformation_H_
#define	_mcm_VruClusterInformation_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier1B.h"
#include "etsi_its_mcm_coding/mcm_CardinalNumber1B.h"
#include "etsi_its_mcm_coding/mcm_VruClusterProfiles.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_Shape;

/* mcm_VruClusterInformation */
typedef struct mcm_VruClusterInformation {
	mcm_Identifier1B_t	*clusterId;	/* OPTIONAL */
	struct mcm_Shape	*clusterBoundingBoxShape;	/* OPTIONAL */
	mcm_CardinalNumber1B_t	 clusterCardinalitySize;
	mcm_VruClusterProfiles_t	*clusterProfiles;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_VruClusterInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VruClusterInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_VruClusterInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_VruClusterInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_Shape.h"

#endif	/* _mcm_VruClusterInformation_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
