/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ParkingSpaceBasic_H_
#define	_mcm_ParkingSpaceBasic_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier2B.h"
#include "etsi_its_mcm_coding/mcm_ParkingSpaceStatus.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_DeltaReferencePosition;

/* mcm_ParkingSpaceBasic */
typedef struct mcm_ParkingSpaceBasic {
	mcm_Identifier2B_t	 id;
	struct mcm_DeltaReferencePosition	*location;	/* OPTIONAL */
	mcm_ParkingSpaceStatus_t	 status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ParkingSpaceBasic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ParkingSpaceBasic;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_ParkingSpaceBasic_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ParkingSpaceBasic_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_DeltaReferencePosition.h"

#endif	/* _mcm_ParkingSpaceBasic_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
