/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_MessageId_H_
#define	_mcm_MessageId_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_MessageId {
	mcm_MessageId_denm	= 1,
	mcm_MessageId_cam	= 2,
	mcm_MessageId_poim	= 3,
	mcm_MessageId_spatem	= 4,
	mcm_MessageId_mapem	= 5,
	mcm_MessageId_ivim	= 6,
	mcm_MessageId_rfu1	= 7,
	mcm_MessageId_rfu2	= 8,
	mcm_MessageId_srem	= 9,
	mcm_MessageId_ssem	= 10,
	mcm_MessageId_evcsn	= 11,
	mcm_MessageId_saem	= 12,
	mcm_MessageId_rtcmem	= 13,
	mcm_MessageId_cpm	= 14,
	mcm_MessageId_imzm	= 15,
	mcm_MessageId_vam	= 16,
	mcm_MessageId_dsm	= 17,
	mcm_MessageId_mim	= 18,
	mcm_MessageId_mvm	= 19,
	mcm_MessageId_mcm	= 20
} e_mcm_MessageId;

/* mcm_MessageId */
typedef long	 mcm_MessageId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_MessageId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_MessageId;
asn_struct_free_f mcm_MessageId_free;
asn_struct_print_f mcm_MessageId_print;
asn_constr_check_f mcm_MessageId_constraint;
jer_type_encoder_f mcm_MessageId_encode_jer;
per_type_decoder_f mcm_MessageId_decode_uper;
per_type_encoder_f mcm_MessageId_encode_uper;
per_type_decoder_f mcm_MessageId_decode_aper;
per_type_encoder_f mcm_MessageId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_MessageId_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
