/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_PositionOfOccupants_H_
#define	_mcm_PositionOfOccupants_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_PositionOfOccupants {
	mcm_PositionOfOccupants_row1LeftOccupied	= 0,
	mcm_PositionOfOccupants_row1RightOccupied	= 1,
	mcm_PositionOfOccupants_row1MidOccupied	= 2,
	mcm_PositionOfOccupants_row1NotDetectable	= 3,
	mcm_PositionOfOccupants_row1NotPresent	= 4,
	mcm_PositionOfOccupants_row2LeftOccupied	= 5,
	mcm_PositionOfOccupants_row2RightOccupied	= 6,
	mcm_PositionOfOccupants_row2MidOccupied	= 7,
	mcm_PositionOfOccupants_row2NotDetectable	= 8,
	mcm_PositionOfOccupants_row2NotPresent	= 9,
	mcm_PositionOfOccupants_row3LeftOccupied	= 10,
	mcm_PositionOfOccupants_row3RightOccupied	= 11,
	mcm_PositionOfOccupants_row3MidOccupied	= 12,
	mcm_PositionOfOccupants_row3NotDetectable	= 13,
	mcm_PositionOfOccupants_row3NotPresent	= 14,
	mcm_PositionOfOccupants_row4LeftOccupied	= 15,
	mcm_PositionOfOccupants_row4RightOccupied	= 16,
	mcm_PositionOfOccupants_row4MidOccupied	= 17,
	mcm_PositionOfOccupants_row4NotDetectable	= 18,
	mcm_PositionOfOccupants_row4NotPresent	= 19
} e_mcm_PositionOfOccupants;

/* mcm_PositionOfOccupants */
typedef BIT_STRING_t	 mcm_PositionOfOccupants_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_PositionOfOccupants;
asn_struct_free_f mcm_PositionOfOccupants_free;
asn_struct_print_f mcm_PositionOfOccupants_print;
asn_constr_check_f mcm_PositionOfOccupants_constraint;
jer_type_encoder_f mcm_PositionOfOccupants_encode_jer;
per_type_decoder_f mcm_PositionOfOccupants_decode_uper;
per_type_encoder_f mcm_PositionOfOccupants_encode_uper;
per_type_decoder_f mcm_PositionOfOccupants_decode_aper;
per_type_encoder_f mcm_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_PositionOfOccupants_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
