/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ItsPduHeader_H_
#define	_mcm_ItsPduHeader_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_OrdinalNumber1B.h"
#include "etsi_its_mcm_coding/mcm_MessageId.h"
#include "etsi_its_mcm_coding/mcm_StationId.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ItsPduHeader */
typedef struct mcm_ItsPduHeader {
	mcm_OrdinalNumber1B_t	 protocolVersion;
	mcm_MessageId_t	 messageId;
	mcm_StationId_t	 stationId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ItsPduHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ItsPduHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_ItsPduHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ItsPduHeader_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ItsPduHeader_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
