/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_StabilityChangeIndication_H_
#define	_mcm_StabilityChangeIndication_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_StabilityLossProbability.h"
#include "etsi_its_mcm_coding/mcm_DeltaTimeTenthOfSecond.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_StabilityChangeIndication */
typedef struct mcm_StabilityChangeIndication {
	mcm_StabilityLossProbability_t	 lossProbability;
	mcm_DeltaTimeTenthOfSecond_t	 actionDeltaTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_StabilityChangeIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_StabilityChangeIndication;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_StabilityChangeIndication_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
