/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ParkingAreaArrangementType_H_
#define	_mcm_ParkingAreaArrangementType_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ParkingAreaArrangementType {
	mcm_ParkingAreaArrangementType_parallelParkingSpace	= 0,
	mcm_ParkingAreaArrangementType_diagonalParkingSpace	= 1,
	mcm_ParkingAreaArrangementType_perpendicularParkingSpace	= 2,
	mcm_ParkingAreaArrangementType_queueParking	= 3,
	mcm_ParkingAreaArrangementType_mixed	= 4,
	mcm_ParkingAreaArrangementType_unknown	= 7
} e_mcm_ParkingAreaArrangementType;

/* mcm_ParkingAreaArrangementType */
typedef long	 mcm_ParkingAreaArrangementType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_ParkingAreaArrangementType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_ParkingAreaArrangementType;
asn_struct_free_f mcm_ParkingAreaArrangementType_free;
asn_struct_print_f mcm_ParkingAreaArrangementType_print;
asn_constr_check_f mcm_ParkingAreaArrangementType_constraint;
jer_type_encoder_f mcm_ParkingAreaArrangementType_encode_jer;
per_type_decoder_f mcm_ParkingAreaArrangementType_decode_uper;
per_type_encoder_f mcm_ParkingAreaArrangementType_encode_uper;
per_type_decoder_f mcm_ParkingAreaArrangementType_decode_aper;
per_type_encoder_f mcm_ParkingAreaArrangementType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ParkingAreaArrangementType_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
