/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_Ext1_H_
#define	_mcm_Ext1_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>
#include "etsi_its_mcm_coding/mcm_Ext2.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_Ext1_PR {
	mcm_Ext1_PR_NOTHING,	/* No components present */
	mcm_Ext1_PR_content,
	mcm_Ext1_PR_extension
} mcm_Ext1_PR;

/* mcm_Ext1 */
typedef struct mcm_Ext1 {
	mcm_Ext1_PR present;
	union mcm_Ext1_u {
		long	 content;
		mcm_Ext2_t	 extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_Ext1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_Ext1;
extern asn_CHOICE_specifics_t asn_SPC_mcm_Ext1_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_Ext1_1[2];
extern asn_per_constraints_t asn_PER_type_mcm_Ext1_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_Ext1_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
