/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_SignalViolationSubCauseCode_H_
#define	_mcm_SignalViolationSubCauseCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_SignalViolationSubCauseCode {
	mcm_SignalViolationSubCauseCode_unavailable	= 0,
	mcm_SignalViolationSubCauseCode_stopSignViolation	= 1,
	mcm_SignalViolationSubCauseCode_trafficLightViolation	= 2,
	mcm_SignalViolationSubCauseCode_turningRegulationViolation	= 3
} e_mcm_SignalViolationSubCauseCode;

/* mcm_SignalViolationSubCauseCode */
typedef long	 mcm_SignalViolationSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_SignalViolationSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_SignalViolationSubCauseCode;
asn_struct_free_f mcm_SignalViolationSubCauseCode_free;
asn_struct_print_f mcm_SignalViolationSubCauseCode_print;
asn_constr_check_f mcm_SignalViolationSubCauseCode_constraint;
jer_type_encoder_f mcm_SignalViolationSubCauseCode_encode_jer;
per_type_decoder_f mcm_SignalViolationSubCauseCode_decode_uper;
per_type_encoder_f mcm_SignalViolationSubCauseCode_encode_uper;
per_type_decoder_f mcm_SignalViolationSubCauseCode_decode_aper;
per_type_encoder_f mcm_SignalViolationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_SignalViolationSubCauseCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
