/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_DangerousGoodsBasic_H_
#define	_mcm_DangerousGoodsBasic_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_DangerousGoodsBasic {
	mcm_DangerousGoodsBasic_explosives1	= 0,
	mcm_DangerousGoodsBasic_explosives2	= 1,
	mcm_DangerousGoodsBasic_explosives3	= 2,
	mcm_DangerousGoodsBasic_explosives4	= 3,
	mcm_DangerousGoodsBasic_explosives5	= 4,
	mcm_DangerousGoodsBasic_explosives6	= 5,
	mcm_DangerousGoodsBasic_flammableGases	= 6,
	mcm_DangerousGoodsBasic_nonFlammableGases	= 7,
	mcm_DangerousGoodsBasic_toxicGases	= 8,
	mcm_DangerousGoodsBasic_flammableLiquids	= 9,
	mcm_DangerousGoodsBasic_flammableSolids	= 10,
	mcm_DangerousGoodsBasic_substancesLiableToSpontaneousCombustion	= 11,
	mcm_DangerousGoodsBasic_substancesEmittingFlammableGasesUponContactWithWater	= 12,
	mcm_DangerousGoodsBasic_oxidizingSubstances	= 13,
	mcm_DangerousGoodsBasic_organicPeroxides	= 14,
	mcm_DangerousGoodsBasic_toxicSubstances	= 15,
	mcm_DangerousGoodsBasic_infectiousSubstances	= 16,
	mcm_DangerousGoodsBasic_radioactiveMaterial	= 17,
	mcm_DangerousGoodsBasic_corrosiveSubstances	= 18,
	mcm_DangerousGoodsBasic_miscellaneousDangerousSubstances	= 19
} e_mcm_DangerousGoodsBasic;

/* mcm_DangerousGoodsBasic */
typedef long	 mcm_DangerousGoodsBasic_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_DangerousGoodsBasic_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_DangerousGoodsBasic;
extern const asn_INTEGER_specifics_t asn_SPC_mcm_DangerousGoodsBasic_specs_1;
asn_struct_free_f mcm_DangerousGoodsBasic_free;
asn_struct_print_f mcm_DangerousGoodsBasic_print;
asn_constr_check_f mcm_DangerousGoodsBasic_constraint;
jer_type_encoder_f mcm_DangerousGoodsBasic_encode_jer;
per_type_decoder_f mcm_DangerousGoodsBasic_decode_uper;
per_type_encoder_f mcm_DangerousGoodsBasic_encode_uper;
per_type_decoder_f mcm_DangerousGoodsBasic_decode_aper;
per_type_encoder_f mcm_DangerousGoodsBasic_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_DangerousGoodsBasic_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
