/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_WiperStatus_H_
#define	_mcm_WiperStatus_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_WiperStatus {
	mcm_WiperStatus_unavailable	= 0,
	mcm_WiperStatus_off	= 1,
	mcm_WiperStatus_intermittent	= 2,
	mcm_WiperStatus_low	= 3,
	mcm_WiperStatus_high	= 4
} e_mcm_WiperStatus;

/* mcm_WiperStatus */
typedef long	 mcm_WiperStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_WiperStatus;
asn_struct_free_f mcm_WiperStatus_free;
asn_struct_print_f mcm_WiperStatus_print;
asn_constr_check_f mcm_WiperStatus_constraint;
jer_type_encoder_f mcm_WiperStatus_encode_jer;
per_type_decoder_f mcm_WiperStatus_decode_uper;
per_type_encoder_f mcm_WiperStatus_encode_uper;
per_type_decoder_f mcm_WiperStatus_decode_aper;
per_type_encoder_f mcm_WiperStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_WiperStatus_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
