/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_VehicleRole_H_
#define	_mcm_VehicleRole_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_VehicleRole {
	mcm_VehicleRole_default	= 0,
	mcm_VehicleRole_publicTransport	= 1,
	mcm_VehicleRole_specialTransport	= 2,
	mcm_VehicleRole_dangerousGoods	= 3,
	mcm_VehicleRole_roadWork	= 4,
	mcm_VehicleRole_rescue	= 5,
	mcm_VehicleRole_emergency	= 6,
	mcm_VehicleRole_safetyCar	= 7,
	mcm_VehicleRole_agriculture	= 8,
	mcm_VehicleRole_commercial	= 9,
	mcm_VehicleRole_military	= 10,
	mcm_VehicleRole_roadOperator	= 11,
	mcm_VehicleRole_taxi	= 12,
	mcm_VehicleRole_uvar	= 13,
	mcm_VehicleRole_rfu1	= 14,
	mcm_VehicleRole_rfu2	= 15
} e_mcm_VehicleRole;

/* mcm_VehicleRole */
typedef long	 mcm_VehicleRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_VehicleRole;
asn_struct_free_f mcm_VehicleRole_free;
asn_struct_print_f mcm_VehicleRole_print;
asn_constr_check_f mcm_VehicleRole_constraint;
jer_type_encoder_f mcm_VehicleRole_encode_jer;
per_type_decoder_f mcm_VehicleRole_decode_uper;
per_type_encoder_f mcm_VehicleRole_encode_uper;
per_type_decoder_f mcm_VehicleRole_decode_aper;
per_type_encoder_f mcm_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_VehicleRole_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
