/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_RadialShapes_H_
#define	_mcm_RadialShapes_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier1B.h"
#include "etsi_its_mcm_coding/mcm_CartesianCoordinateSmall.h"
#include "etsi_its_mcm_coding/mcm_RadialShapesList.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_RadialShapes */
typedef struct mcm_RadialShapes {
	mcm_Identifier1B_t	 refPointId;
	mcm_CartesianCoordinateSmall_t	 xCoordinate;
	mcm_CartesianCoordinateSmall_t	 yCoordinate;
	mcm_CartesianCoordinateSmall_t	*zCoordinate;	/* OPTIONAL */
	mcm_RadialShapesList_t	 radialShapesList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_RadialShapes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_RadialShapes;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_RadialShapes_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_RadialShapes_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_RadialShapes_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
