/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_WayPointType_H_
#define	_mcm_WayPointType_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_WayPointType {
	mcm_WayPointType_startingWayPoint	= 0,
	mcm_WayPointType_intermediateWayPoint	= 1,
	mcm_WayPointType_endingWayPoint	= 2
} e_mcm_WayPointType;

/* mcm_WayPointType */
typedef long	 mcm_WayPointType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_WayPointType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_WayPointType;
extern const asn_INTEGER_specifics_t asn_SPC_mcm_WayPointType_specs_1;
asn_struct_free_f mcm_WayPointType_free;
asn_struct_print_f mcm_WayPointType_print;
asn_constr_check_f mcm_WayPointType_constraint;
jer_type_encoder_f mcm_WayPointType_encode_jer;
per_type_decoder_f mcm_WayPointType_decode_uper;
per_type_encoder_f mcm_WayPointType_encode_uper;
per_type_decoder_f mcm_WayPointType_decode_aper;
per_type_encoder_f mcm_WayPointType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_WayPointType_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
