/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_BasicLaneInformation_H_
#define	_mcm_BasicLaneInformation_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_LanePosition.h"
#include "etsi_its_mcm_coding/mcm_Direction.h"
#include "etsi_its_mcm_coding/mcm_LaneWidth.h"
#include "etsi_its_mcm_coding/mcm_RoadSectionId.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_BasicLaneInformation */
typedef struct mcm_BasicLaneInformation {
	mcm_LanePosition_t	 laneNumber;
	mcm_Direction_t	 direction;
	mcm_LaneWidth_t	*laneWidth;	/* OPTIONAL */
	mcm_LanePosition_t	*connectingLane;	/* OPTIONAL */
	mcm_RoadSectionId_t	*connectingRoadSection;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_BasicLaneInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_BasicLaneInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_BasicLaneInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_BasicLaneInformation_1[5];
extern asn_per_constraints_t asn_PER_type_mcm_BasicLaneInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_BasicLaneInformation_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
