/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ObjectPerceptionQuality_H_
#define	_mcm_ObjectPerceptionQuality_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ObjectPerceptionQuality {
	mcm_ObjectPerceptionQuality_noConfidence	= 0,
	mcm_ObjectPerceptionQuality_fullConfidence	= 15
} e_mcm_ObjectPerceptionQuality;

/* mcm_ObjectPerceptionQuality */
typedef long	 mcm_ObjectPerceptionQuality_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_ObjectPerceptionQuality_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_ObjectPerceptionQuality;
asn_struct_free_f mcm_ObjectPerceptionQuality_free;
asn_struct_print_f mcm_ObjectPerceptionQuality_print;
asn_constr_check_f mcm_ObjectPerceptionQuality_constraint;
jer_type_encoder_f mcm_ObjectPerceptionQuality_encode_jer;
per_type_decoder_f mcm_ObjectPerceptionQuality_decode_uper;
per_type_encoder_f mcm_ObjectPerceptionQuality_encode_uper;
per_type_decoder_f mcm_ObjectPerceptionQuality_decode_aper;
per_type_encoder_f mcm_ObjectPerceptionQuality_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ObjectPerceptionQuality_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
