/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_EuVehicleCategoryCode_H_
#define	_mcm_EuVehicleCategoryCode_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_EuVehicleCategoryL.h"
#include "etsi_its_mcm_coding/mcm_EuVehicleCategoryM.h"
#include "etsi_its_mcm_coding/mcm_EuVehicleCategoryN.h"
#include "etsi_its_mcm_coding/mcm_EuVehicleCategoryO.h"
#include <etsi_its_mcm_coding/NULL.h>
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_EuVehicleCategoryCode_PR {
	mcm_EuVehicleCategoryCode_PR_NOTHING,	/* No components present */
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryL,
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryM,
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryN,
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryO,
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryT,
	mcm_EuVehicleCategoryCode_PR_euVehicleCategoryG
} mcm_EuVehicleCategoryCode_PR;

/* mcm_EuVehicleCategoryCode */
typedef struct mcm_EuVehicleCategoryCode {
	mcm_EuVehicleCategoryCode_PR present;
	union mcm_EuVehicleCategoryCode_u {
		mcm_EuVehicleCategoryL_t	 euVehicleCategoryL;
		mcm_EuVehicleCategoryM_t	 euVehicleCategoryM;
		mcm_EuVehicleCategoryN_t	 euVehicleCategoryN;
		mcm_EuVehicleCategoryO_t	 euVehicleCategoryO;
		NULL_t	 euVehicleCategoryT;
		NULL_t	 euVehicleCategoryG;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_EuVehicleCategoryCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_EuVehicleCategoryCode;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_EuVehicleCategoryCode_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
