/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_Submanoeuvre_H_
#define	_mcm_Submanoeuvre_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier1B.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_Trajectory;
struct mcm_AdvisedTrrContainer;

/* mcm_Submanoeuvre */
typedef struct mcm_Submanoeuvre {
	mcm_Identifier1B_t	 submanoeuvreId;
	struct mcm_Trajectory	*advisedTrajectory;	/* OPTIONAL */
	struct mcm_AdvisedTrrContainer	*advisedTargetRoadResource;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_Submanoeuvre_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_Submanoeuvre;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_Submanoeuvre_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_Submanoeuvre_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_Trajectory.h"
#include "etsi_its_mcm_coding/mcm_AdvisedTrrContainer.h"

#endif	/* _mcm_Submanoeuvre_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
