/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ParkingSpaceDetailed_H_
#define	_mcm_ParkingSpaceDetailed_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier2B.h"
#include "etsi_its_mcm_coding/mcm_ParkingSpaceStatus.h"
#include "etsi_its_mcm_coding/mcm_ParkingAreaArrangementType.h"
#include "etsi_its_mcm_coding/mcm_ParkingOccupancyInfo.h"
#include <etsi_its_mcm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_coding/constr_SEQUENCE_OF.h>
#include "etsi_its_mcm_coding/mcm_ParkingReservationType.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_DeltaReferencePosition;
struct mcm_DeltaPositions;
struct mcm_Wgs84Angle;

/* mcm_ParkingSpaceDetailed */
typedef struct mcm_ParkingSpaceDetailed {
	mcm_Identifier2B_t	 id;
	struct mcm_DeltaReferencePosition	*location;	/* OPTIONAL */
	mcm_ParkingSpaceStatus_t	 status;
	mcm_ParkingAreaArrangementType_t	*arrangementType;	/* OPTIONAL */
	struct mcm_DeltaPositions	*boundary;	/* OPTIONAL */
	struct mcm_Wgs84Angle	*orientation;	/* OPTIONAL */
	mcm_ParkingOccupancyInfo_t	 occupancyRule;
	mcm_Identifier2B_t	*chargingStationId;	/* OPTIONAL */
	mcm_Identifier2B_t	*accessViaLane;	/* OPTIONAL */
	struct mcm_ParkingSpaceDetailed__accessViaParkingSpaces {
		A_SEQUENCE_OF(mcm_Identifier2B_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accessViaParkingSpaces;
	struct mcm_ParkingSpaceDetailed__reservationType {
		A_SEQUENCE_OF(mcm_ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ParkingSpaceDetailed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ParkingSpaceDetailed;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_DeltaReferencePosition.h"
#include "etsi_its_mcm_coding/mcm_DeltaPositions.h"
#include "etsi_its_mcm_coding/mcm_Wgs84Angle.h"

#endif	/* _mcm_ParkingSpaceDetailed_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
