/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_McmBasicContainer_H_
#define	_mcm_McmBasicContainer_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_GenerationDeltaTime.h"
#include "etsi_its_mcm_coding/mcm_McmStationType.h"
#include "etsi_its_mcm_coding/mcm_McmItssRole.h"
#include "etsi_its_mcm_coding/mcm_ReferencePosition.h"
#include "etsi_its_mcm_coding/mcm_McmContainer.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_McmBasicContainer */
typedef struct mcm_McmBasicContainer {
	mcm_GenerationDeltaTime_t	 generationDeltaTime;
	mcm_McmStationType_t	 stationType;
	mcm_McmItssRole_t	 itssRole;
	mcm_ReferencePosition_t	 position;
	mcm_McmContainer_t	 mcmData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_McmBasicContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_McmBasicContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_McmBasicContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_McmBasicContainer_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_McmBasicContainer_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
