/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_WayPoint_H_
#define	_mcm_WayPoint_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_WayPoint */
typedef NULL_t	 mcm_WayPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_WayPoint;
asn_struct_free_f mcm_WayPoint_free;
asn_struct_print_f mcm_WayPoint_print;
asn_constr_check_f mcm_WayPoint_constraint;
jer_type_encoder_f mcm_WayPoint_encode_jer;
per_type_decoder_f mcm_WayPoint_decode_uper;
per_type_encoder_f mcm_WayPoint_encode_uper;
per_type_decoder_f mcm_WayPoint_decode_aper;
per_type_encoder_f mcm_WayPoint_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_WayPoint_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
