/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ClusterBreakupInfo_H_
#define	_mcm_ClusterBreakupInfo_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_ClusterBreakupReason.h"
#include "etsi_its_mcm_coding/mcm_DeltaTimeQuarterSecond.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ClusterBreakupInfo */
typedef struct mcm_ClusterBreakupInfo {
	mcm_ClusterBreakupReason_t	 clusterBreakupReason;
	mcm_DeltaTimeQuarterSecond_t	 breakupTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ClusterBreakupInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ClusterBreakupInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ClusterBreakupInfo_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
