/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_SubmanoeuvreDescription_H_
#define	_mcm_SubmanoeuvreDescription_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_Identifier1B.h"
#include "etsi_its_mcm_coding/mcm_TemporalCharacteristics.h"
#include "etsi_its_mcm_coding/mcm_KinematicsCharacteristics.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_SubmanoeuvreStrategy;
struct mcm_Trajectory;
struct mcm_TrrDescription;

/* mcm_SubmanoeuvreDescription */
typedef struct mcm_SubmanoeuvreDescription {
	mcm_Identifier1B_t	 submanoeuvreID;
	struct mcm_SubmanoeuvreStrategy	*submanoeuvreStrategy;	/* OPTIONAL */
	struct mcm_Trajectory	*referenceTrajectory;	/* OPTIONAL */
	struct mcm_TrrDescription	*targetRoadResourceIContainer;	/* OPTIONAL */
	mcm_TemporalCharacteristics_t	 temporalCharateristics;
	mcm_KinematicsCharacteristics_t	 kinematicsCharacteristics;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_SubmanoeuvreDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_SubmanoeuvreDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_SubmanoeuvreDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_SubmanoeuvreDescription_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_SubmanoeuvreStrategy.h"
#include "etsi_its_mcm_coding/mcm_Trajectory.h"
#include "etsi_its_mcm_coding/mcm_TrrDescription.h"

#endif	/* _mcm_SubmanoeuvreDescription_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
