/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_McmGenericCurentStateContainer_H_
#define	_mcm_McmGenericCurentStateContainer_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_coding/mcm_McmType.h"
#include "etsi_its_mcm_coding/mcm_ManoeuvreId.h"
#include "etsi_its_mcm_coding/mcm_ManoeuvreCoordinationConcept.h"
#include "etsi_its_mcm_coding/mcm_ManoeuvreExecutionStatus.h"
#include <etsi_its_mcm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct mcm_ManoeuvreCoordinationRational;

/* mcm_McmGenericCurentStateContainer */
typedef struct mcm_McmGenericCurentStateContainer {
	mcm_McmType_t	 mcmType;
	mcm_ManoeuvreId_t	 manoeuvreId;
	mcm_ManoeuvreCoordinationConcept_t	 concept;
	struct mcm_ManoeuvreCoordinationRational	*rational;	/* OPTIONAL */
	mcm_ManoeuvreExecutionStatus_t	*executionStatus;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_McmGenericCurentStateContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_McmGenericCurentStateContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_mcm_McmGenericCurentStateContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_McmGenericCurentStateContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_coding/mcm_ManoeuvreCoordinationRational.h"

#endif	/* _mcm_McmGenericCurentStateContainer_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
