/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_ParkingOccupancyInfo_H_
#define	_mcm_ParkingOccupancyInfo_H_


#include <etsi_its_mcm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_coding/NULL.h>
#include <etsi_its_mcm_coding/NativeInteger.h>
#include "etsi_its_mcm_coding/mcm_TimestampIts.h"
#include <etsi_its_mcm_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ParkingOccupancyInfo_PR {
	mcm_ParkingOccupancyInfo_PR_NOTHING,	/* No components present */
	mcm_ParkingOccupancyInfo_PR_unknown,
	mcm_ParkingOccupancyInfo_PR_unlimitedOccupancy,
	mcm_ParkingOccupancyInfo_PR_onlyWhileCharging,
	mcm_ParkingOccupancyInfo_PR_limitedDuration,
	mcm_ParkingOccupancyInfo_PR_onlyWhileChargingLimitedDuration,
	mcm_ParkingOccupancyInfo_PR_parkingAllowedUntil,
	mcm_ParkingOccupancyInfo_PR_forcedParkingUntil
	/* Extensions may appear below */
	
} mcm_ParkingOccupancyInfo_PR;

/* mcm_ParkingOccupancyInfo */
typedef struct mcm_ParkingOccupancyInfo {
	mcm_ParkingOccupancyInfo_PR present;
	union mcm_ParkingOccupancyInfo_u {
		NULL_t	 unknown;
		NULL_t	 unlimitedOccupancy;
		NULL_t	 onlyWhileCharging;
		long	 limitedDuration;
		long	 onlyWhileChargingLimitedDuration;
		mcm_TimestampIts_t	 parkingAllowedUntil;
		mcm_TimestampIts_t	 forcedParkingUntil;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ParkingOccupancyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ParkingOccupancyInfo;
extern asn_CHOICE_specifics_t asn_SPC_mcm_ParkingOccupancyInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_mcm_ParkingOccupancyInfo_1[7];
extern asn_per_constraints_t asn_PER_type_mcm_ParkingOccupancyInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ParkingOccupancyInfo_H_ */
#include <etsi_its_mcm_coding/asn_internal.h>
