/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
TrrDescription ::= SEQUENCE {
	trrType TrrType,
	laneCount LaneCount, -- Number of adjacent lanes covered by the TRR surface from the starting lane number with a relavive position for each one
	startingLaneNumber LaneCount OPTIONAL, --: identification of the lane in which the executant vehicle starts the submanoeuvre
	endingLaneNumber LaneCount OPTIONAL, -- Identification of the lane in which the executant vehicle ends the submanoeuvre
	waypoints SEQUENCE (SIZE (2..16)) OF WayPoint OPTIONAL, -- At least the starting and ending waypoints used to specify the length of the covered TRR. Optional intermediary waypoints can be added
	heading SEQUENCE (SIZE (2..16)) OF Wgs84Angle OPTIONAL, -- At the level of all identified waypoints
	trrWidth TRRWidth, -- computed from the lane count
	trrLength TRRLength -- computed distance between the starting and ending waypoints
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_TrrDescription.h>
#include <etsi_its_mcm_conversion/convertLaneCount.h>
#include <etsi_its_mcm_conversion/convertTRRLength.h>
#include <etsi_its_mcm_conversion/convertTRRWidth.h>
#include <etsi_its_mcm_conversion/convertTrrType.h>
#include <etsi_its_mcm_conversion/convertWayPoint.h>
#include <etsi_its_mcm_conversion/convertWgs84Angle.h>
#include <etsi_its_mcm_msgs/msg/trr_description.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_TrrDescription(const mcm_TrrDescription_t& in, mcm_msgs::TrrDescription& out) {
  toRos_TrrType(in.trrType, out.trr_type);
  toRos_LaneCount(in.laneCount, out.lane_count);
  if (in.startingLaneNumber) {
    toRos_LaneCount(*in.startingLaneNumber, out.starting_lane_number);
    out.starting_lane_number_is_present = true;
  }
  if (in.endingLaneNumber) {
    toRos_LaneCount(*in.endingLaneNumber, out.ending_lane_number);
    out.ending_lane_number_is_present = true;
  }
  if (in.waypoints) {
    for (int i = 0; i < in.waypoints->list.count; ++i) {
      mcm_msgs::WayPoint el;
      toRos_WayPoint(*(in.waypoints->list.array[i]), el);
      out.waypoints.push_back(el);
    }
    out.waypoints_is_present = true;
  }
  if (in.heading) {
    for (int i = 0; i < in.heading->list.count; ++i) {
      mcm_msgs::Wgs84Angle el;
      toRos_Wgs84Angle(*(in.heading->list.array[i]), el);
      out.heading.push_back(el);
    }
    out.heading_is_present = true;
  }
  toRos_TRRWidth(in.trrWidth, out.trr_width);
  toRos_TRRLength(in.trrLength, out.trr_length);
}

void toStruct_TrrDescription(const mcm_msgs::TrrDescription& in, mcm_TrrDescription_t& out) {
  memset(&out, 0, sizeof(mcm_TrrDescription_t));
  toStruct_TrrType(in.trr_type, out.trrType);
  toStruct_LaneCount(in.lane_count, out.laneCount);
  if (in.starting_lane_number_is_present) {
    out.startingLaneNumber = (mcm_LaneCount_t*) calloc(1, sizeof(mcm_LaneCount_t));
    toStruct_LaneCount(in.starting_lane_number, *out.startingLaneNumber);
  }
  if (in.ending_lane_number_is_present) {
    out.endingLaneNumber = (mcm_LaneCount_t*) calloc(1, sizeof(mcm_LaneCount_t));
    toStruct_LaneCount(in.ending_lane_number, *out.endingLaneNumber);
  }
  if (in.waypoints_is_present) {
    for (int i = 0; i < in.waypoints.size(); ++i) {
      mcm_WayPoint_t* el = (mcm_WayPoint_t*) calloc(1, sizeof(mcm_WayPoint_t));
      toStruct_WayPoint(in.waypoints[i], *el);
      if (asn_sequence_add(&out.waypoints, el)) throw std::invalid_argument("Failed to add to A_SEQUENCE_OF");
    }
  }
  if (in.heading_is_present) {
    for (int i = 0; i < in.heading.size(); ++i) {
      mcm_Wgs84Angle_t* el = (mcm_Wgs84Angle_t*) calloc(1, sizeof(mcm_Wgs84Angle_t));
      toStruct_Wgs84Angle(in.heading[i], *el);
      if (asn_sequence_add(&out.heading, el)) throw std::invalid_argument("Failed to add to A_SEQUENCE_OF");
    }
  }
  toStruct_TRRWidth(in.trr_width, out.trrWidth);
  toStruct_TRRLength(in.trr_length, out.trrLength);
}

}
