/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
McmContainer ::= CHOICE {
	vehicleManoeuvreContainer VehicleManoeuvreContainer,
	advisedManoeuvreContainer ManoeuvreAdviceContainer
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_McmContainer.h>
#include <etsi_its_mcm_conversion/convertManoeuvreAdviceContainer.h>
#include <etsi_its_mcm_conversion/convertVehicleManoeuvreContainer.h>
#include <etsi_its_mcm_msgs/msg/mcm_container.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_McmContainer(const mcm_McmContainer_t& in, mcm_msgs::McmContainer& out) {
  switch (in.present) {
  case mcm_McmContainer_PR_vehicleManoeuvreContainer:
    toRos_VehicleManoeuvreContainer(in.choice.vehicleManoeuvreContainer, out.vehicle_manoeuvre_container);
    out.choice = mcm_msgs::McmContainer::CHOICE_VEHICLE_MANOEUVRE_CONTAINER;
    break;
  case mcm_McmContainer_PR_advisedManoeuvreContainer:
    toRos_ManoeuvreAdviceContainer(in.choice.advisedManoeuvreContainer, out.advised_manoeuvre_container);
    out.choice = mcm_msgs::McmContainer::CHOICE_ADVISED_MANOEUVRE_CONTAINER;
    break;
  default: break;
  }
}

void toStruct_McmContainer(const mcm_msgs::McmContainer& in, mcm_McmContainer_t& out) {
  memset(&out, 0, sizeof(mcm_McmContainer_t));
  switch (in.choice) {
  case mcm_msgs::McmContainer::CHOICE_VEHICLE_MANOEUVRE_CONTAINER:
    toStruct_VehicleManoeuvreContainer(in.vehicle_manoeuvre_container, out.choice.vehicleManoeuvreContainer);
    out.present = mcm_McmContainer_PR::mcm_McmContainer_PR_vehicleManoeuvreContainer;
    break;
  case mcm_msgs::McmContainer::CHOICE_ADVISED_MANOEUVRE_CONTAINER:
    toStruct_ManoeuvreAdviceContainer(in.advised_manoeuvre_container, out.choice.advisedManoeuvreContainer);
    out.present = mcm_McmContainer_PR::mcm_McmContainer_PR_advisedManoeuvreContainer;
    break;
  default: break;
  }
}

}
