/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
McmGenericCurentStateContainer::= SEQUENCE {
	mcmType McmType, -- type of manoeuvre coordination message
	manoeuvreId ManoeuvreId, -- MCS session ID (its-s ID provided in header and integer modulo 256)
	concept ManoeuvreCoordinationConcept,
	rational ManoeuvreCoordinationRational OPTIONAL, -- Rational to be associated to an offer, intent, advice or a request. Depending on the manoeuvre coordination concept being used.
													 -- For agreement seeking concept the cooperationCost rational can be provided (optional),
													 -- while for the prescriptive concept, the cooperationGoal rational shall be provided
	executionStatus ManoeuvreExecutionStatus OPTIONAL -- Only present in MCM type 7 and type 4
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_McmGenericCurentStateContainer.h>
#include <etsi_its_mcm_conversion/convertManoeuvreCoordinationConcept.h>
#include <etsi_its_mcm_conversion/convertManoeuvreCoordinationRational.h>
#include <etsi_its_mcm_conversion/convertManoeuvreExecutionStatus.h>
#include <etsi_its_mcm_conversion/convertManoeuvreId.h>
#include <etsi_its_mcm_conversion/convertMcmType.h>
#include <etsi_its_mcm_msgs/msg/mcm_generic_curent_state_container.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_McmGenericCurentStateContainer(const mcm_McmGenericCurentStateContainer_t& in, mcm_msgs::McmGenericCurentStateContainer& out) {
  toRos_McmType(in.mcmType, out.mcm_type);
  toRos_ManoeuvreId(in.manoeuvreId, out.manoeuvre_id);
  toRos_ManoeuvreCoordinationConcept(in.concept, out.concept);
  if (in.rational) {
    toRos_ManoeuvreCoordinationRational(*in.rational, out.rational);
    out.rational_is_present = true;
  }
  if (in.executionStatus) {
    toRos_ManoeuvreExecutionStatus(*in.executionStatus, out.execution_status);
    out.execution_status_is_present = true;
  }
}

void toStruct_McmGenericCurentStateContainer(const mcm_msgs::McmGenericCurentStateContainer& in, mcm_McmGenericCurentStateContainer_t& out) {
  memset(&out, 0, sizeof(mcm_McmGenericCurentStateContainer_t));
  toStruct_McmType(in.mcm_type, out.mcmType);
  toStruct_ManoeuvreId(in.manoeuvre_id, out.manoeuvreId);
  toStruct_ManoeuvreCoordinationConcept(in.concept, out.concept);
  if (in.rational_is_present) {
    out.rational = (mcm_ManoeuvreCoordinationRational_t*) calloc(1, sizeof(mcm_ManoeuvreCoordinationRational_t));
    toStruct_ManoeuvreCoordinationRational(in.rational, *out.rational);
  }
  if (in.execution_status_is_present) {
    out.executionStatus = (mcm_ManoeuvreExecutionStatus_t*) calloc(1, sizeof(mcm_ManoeuvreExecutionStatus_t));
    toStruct_ManoeuvreExecutionStatus(in.execution_status, *out.executionStatus);
  }
}

}
