/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
CurrentStateAdvisedChange::= CHOICE {
	transitToHumanDrivingMode NULL,
	transitToAutomatedDrivingMode NULL,
	followMeWithMinTimeInterDistance INTEGER (300..2000), -- in Milliseconds
	joinGroup JoinGroupStateChange,
	leaveGroup NULL,
	emergencyBrakeTriggering NULL,
	stayInLane NULL,
	stop NULL,
	resetStop NULL,
	resetStayInLane NULL,
	stayAwayOfVehicleSithStationID NULL,
	resetStayAwayOfVehicle NULL
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_CurrentStateAdvisedChange.h>
#include <etsi_its_mcm_conversion/convertuint16.h>
#include <etsi_its_mcm_conversion/convertJoinGroupStateChange.h>
#include <etsi_its_mcm_msgs/msg/current_state_advised_change.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_CurrentStateAdvisedChange(const mcm_CurrentStateAdvisedChange_t& in, mcm_msgs::CurrentStateAdvisedChange& out) {
  switch (in.present) {
  case mcm_CurrentStateAdvisedChange_PR_transitToHumanDrivingMode:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_TRANSIT_TO_HUMAN_DRIVING_MODE;
    break;
  case mcm_CurrentStateAdvisedChange_PR_transitToAutomatedDrivingMode:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_TRANSIT_TO_AUTOMATED_DRIVING_MODE;
    break;
  case mcm_CurrentStateAdvisedChange_PR_followMeWithMinTimeInterDistance:
    toRos_uint16(in.choice.followMeWithMinTimeInterDistance, out.follow_me_with_min_time_inter_distance);
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_FOLLOW_ME_WITH_MIN_TIME_INTER_DISTANCE;
    break;
  case mcm_CurrentStateAdvisedChange_PR_joinGroup:
    toRos_JoinGroupStateChange(in.choice.joinGroup, out.join_group);
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_JOIN_GROUP;
    break;
  case mcm_CurrentStateAdvisedChange_PR_leaveGroup:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_LEAVE_GROUP;
    break;
  case mcm_CurrentStateAdvisedChange_PR_emergencyBrakeTriggering:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_EMERGENCY_BRAKE_TRIGGERING;
    break;
  case mcm_CurrentStateAdvisedChange_PR_stayInLane:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_STAY_IN_LANE;
    break;
  case mcm_CurrentStateAdvisedChange_PR_stop:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_STOP;
    break;
  case mcm_CurrentStateAdvisedChange_PR_resetStop:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STOP;
    break;
  case mcm_CurrentStateAdvisedChange_PR_resetStayInLane:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STAY_IN_LANE;
    break;
  case mcm_CurrentStateAdvisedChange_PR_stayAwayOfVehicleSithStationID:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_STAY_AWAY_OF_VEHICLE_SITH_STATION_ID;
    break;
  case mcm_CurrentStateAdvisedChange_PR_resetStayAwayOfVehicle:
    out.choice = mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STAY_AWAY_OF_VEHICLE;
    break;
  default: break;
  }
}

void toStruct_CurrentStateAdvisedChange(const mcm_msgs::CurrentStateAdvisedChange& in, mcm_CurrentStateAdvisedChange_t& out) {
  memset(&out, 0, sizeof(mcm_CurrentStateAdvisedChange_t));
  switch (in.choice) {
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_TRANSIT_TO_HUMAN_DRIVING_MODE:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_transitToHumanDrivingMode;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_TRANSIT_TO_AUTOMATED_DRIVING_MODE:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_transitToAutomatedDrivingMode;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_FOLLOW_ME_WITH_MIN_TIME_INTER_DISTANCE:
    toStruct_uint16(in.follow_me_with_min_time_inter_distance, out.choice.followMeWithMinTimeInterDistance);
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_followMeWithMinTimeInterDistance;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_JOIN_GROUP:
    toStruct_JoinGroupStateChange(in.join_group, out.choice.joinGroup);
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_joinGroup;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_LEAVE_GROUP:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_leaveGroup;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_EMERGENCY_BRAKE_TRIGGERING:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_emergencyBrakeTriggering;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_STAY_IN_LANE:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_stayInLane;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_STOP:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_stop;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STOP:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_resetStop;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STAY_IN_LANE:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_resetStayInLane;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_STAY_AWAY_OF_VEHICLE_SITH_STATION_ID:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_stayAwayOfVehicleSithStationID;
    break;
  case mcm_msgs::CurrentStateAdvisedChange::CHOICE_RESET_STAY_AWAY_OF_VEHICLE:
    out.present = mcm_CurrentStateAdvisedChange_PR::mcm_CurrentStateAdvisedChange_PR_resetStayAwayOfVehicle;
    break;
  default: break;
  }
}

}
