/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
McmBasicContainer ::= SEQUENCE {
	generationDeltaTime GenerationDeltaTime,
	stationType McmStationType, -- Type of originating ITS-S (VRU Portable Device, vehicle (vehicle type) or roadside unit or central station)
	itssRole McmItssRole, -- The role of the originating ITS-S can only be identified once the MC is accepted by all relevant participants
	position ReferencePosition, -- Time relative delta of the latest WGS84 geographic position of the originating ITS-S as obtained by the MCS at the time of MCM generation (only for vehicle ITS-S)
	mcmData McmContainer
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_McmBasicContainer.h>
#include <etsi_its_mcm_conversion/convertGenerationDeltaTime.h>
#include <etsi_its_mcm_conversion/convertMcmContainer.h>
#include <etsi_its_mcm_conversion/convertMcmItssRole.h>
#include <etsi_its_mcm_conversion/convertMcmStationType.h>
#include <etsi_its_mcm_conversion/convertReferencePosition.h>
#include <etsi_its_mcm_msgs/msg/mcm_basic_container.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_McmBasicContainer(const mcm_McmBasicContainer_t& in, mcm_msgs::McmBasicContainer& out) {
  toRos_GenerationDeltaTime(in.generationDeltaTime, out.generation_delta_time);
  toRos_McmStationType(in.stationType, out.station_type);
  toRos_McmItssRole(in.itssRole, out.itss_role);
  toRos_ReferencePosition(in.position, out.position);
  toRos_McmContainer(in.mcmData, out.mcm_data);
}

void toStruct_McmBasicContainer(const mcm_msgs::McmBasicContainer& in, mcm_McmBasicContainer_t& out) {
  memset(&out, 0, sizeof(mcm_McmBasicContainer_t));
  toStruct_GenerationDeltaTime(in.generation_delta_time, out.generationDeltaTime);
  toStruct_McmStationType(in.station_type, out.stationType);
  toStruct_McmItssRole(in.itss_role, out.itssRole);
  toStruct_ReferencePosition(in.position, out.position);
  toStruct_McmContainer(in.mcm_data, out.mcmData);
}

}
