/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
SubmanoeuvreStrategy::= CHOICE {
	undefined NULL,
	transitToHumanDrivenMode NULL,
	transitToAutomatedDrivingMode NULL,
	driveStraight NULL,
	turnLeft NULL,
	turnRight NULL,
	uTurn NULL,
	moveBackward NULL,
	overtake NULL,
	accelerate NULL,
	slowDown NULL,
	stop NULL,
	goToLeftLane NULL,
	goToRightLane NULL,
	getOnHighway NULL,
	exitHighway NULL,
	takeTollingLane INTEGER (1..31), -- laneNumber
	stopAndWait NULL,
	emergencyBrakeAndStop NULL,
	resetStopAndRestartMoving NULL,
	stayInLane NULL,
	resetStayInLane NULL,
	stayAway NULL,
	resetStayAway NULL,
	followMe NULL,
	existingGroup NULL,
	temporarilyDisbandAnExistingGroup NULL,
	constituteATemporarilyGroup NULL,
	disbandATemporarilyGroup NULL
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_SubmanoeuvreStrategy.h>
#include <etsi_its_mcm_conversion/convertuint8.h>
#include <etsi_its_mcm_msgs/msg/submanoeuvre_strategy.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_SubmanoeuvreStrategy(const mcm_SubmanoeuvreStrategy_t& in, mcm_msgs::SubmanoeuvreStrategy& out) {
  switch (in.present) {
  case mcm_SubmanoeuvreStrategy_PR_undefined:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_UNDEFINED;
    break;
  case mcm_SubmanoeuvreStrategy_PR_transitToHumanDrivenMode:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TRANSIT_TO_HUMAN_DRIVEN_MODE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_transitToAutomatedDrivingMode:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TRANSIT_TO_AUTOMATED_DRIVING_MODE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_driveStraight:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_DRIVE_STRAIGHT;
    break;
  case mcm_SubmanoeuvreStrategy_PR_turnLeft:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TURN_LEFT;
    break;
  case mcm_SubmanoeuvreStrategy_PR_turnRight:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TURN_RIGHT;
    break;
  case mcm_SubmanoeuvreStrategy_PR_uTurn:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_U_TURN;
    break;
  case mcm_SubmanoeuvreStrategy_PR_moveBackward:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_MOVE_BACKWARD;
    break;
  case mcm_SubmanoeuvreStrategy_PR_overtake:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_OVERTAKE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_accelerate:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_ACCELERATE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_slowDown:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_SLOW_DOWN;
    break;
  case mcm_SubmanoeuvreStrategy_PR_stop:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_STOP;
    break;
  case mcm_SubmanoeuvreStrategy_PR_goToLeftLane:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_GO_TO_LEFT_LANE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_goToRightLane:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_GO_TO_RIGHT_LANE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_getOnHighway:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_GET_ON_HIGHWAY;
    break;
  case mcm_SubmanoeuvreStrategy_PR_exitHighway:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_EXIT_HIGHWAY;
    break;
  case mcm_SubmanoeuvreStrategy_PR_takeTollingLane:
    toRos_uint8(in.choice.takeTollingLane, out.take_tolling_lane);
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TAKE_TOLLING_LANE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_stopAndWait:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_STOP_AND_WAIT;
    break;
  case mcm_SubmanoeuvreStrategy_PR_emergencyBrakeAndStop:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_EMERGENCY_BRAKE_AND_STOP;
    break;
  case mcm_SubmanoeuvreStrategy_PR_resetStopAndRestartMoving:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STOP_AND_RESTART_MOVING;
    break;
  case mcm_SubmanoeuvreStrategy_PR_stayInLane:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_STAY_IN_LANE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_resetStayInLane:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STAY_IN_LANE;
    break;
  case mcm_SubmanoeuvreStrategy_PR_stayAway:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_STAY_AWAY;
    break;
  case mcm_SubmanoeuvreStrategy_PR_resetStayAway:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STAY_AWAY;
    break;
  case mcm_SubmanoeuvreStrategy_PR_followMe:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_FOLLOW_ME;
    break;
  case mcm_SubmanoeuvreStrategy_PR_existingGroup:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_EXISTING_GROUP;
    break;
  case mcm_SubmanoeuvreStrategy_PR_temporarilyDisbandAnExistingGroup:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_TEMPORARILY_DISBAND_AN_EXISTING_GROUP;
    break;
  case mcm_SubmanoeuvreStrategy_PR_constituteATemporarilyGroup:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_CONSTITUTE_A_TEMPORARILY_GROUP;
    break;
  case mcm_SubmanoeuvreStrategy_PR_disbandATemporarilyGroup:
    out.choice = mcm_msgs::SubmanoeuvreStrategy::CHOICE_DISBAND_A_TEMPORARILY_GROUP;
    break;
  default: break;
  }
}

void toStruct_SubmanoeuvreStrategy(const mcm_msgs::SubmanoeuvreStrategy& in, mcm_SubmanoeuvreStrategy_t& out) {
  memset(&out, 0, sizeof(mcm_SubmanoeuvreStrategy_t));
  switch (in.choice) {
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_UNDEFINED:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_undefined;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TRANSIT_TO_HUMAN_DRIVEN_MODE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_transitToHumanDrivenMode;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TRANSIT_TO_AUTOMATED_DRIVING_MODE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_transitToAutomatedDrivingMode;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_DRIVE_STRAIGHT:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_driveStraight;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TURN_LEFT:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_turnLeft;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TURN_RIGHT:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_turnRight;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_U_TURN:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_uTurn;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_MOVE_BACKWARD:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_moveBackward;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_OVERTAKE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_overtake;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_ACCELERATE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_accelerate;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_SLOW_DOWN:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_slowDown;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_STOP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_stop;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_GO_TO_LEFT_LANE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_goToLeftLane;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_GO_TO_RIGHT_LANE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_goToRightLane;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_GET_ON_HIGHWAY:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_getOnHighway;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_EXIT_HIGHWAY:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_exitHighway;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TAKE_TOLLING_LANE:
    toStruct_uint8(in.take_tolling_lane, out.choice.takeTollingLane);
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_takeTollingLane;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_STOP_AND_WAIT:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_stopAndWait;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_EMERGENCY_BRAKE_AND_STOP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_emergencyBrakeAndStop;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STOP_AND_RESTART_MOVING:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_resetStopAndRestartMoving;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_STAY_IN_LANE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_stayInLane;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STAY_IN_LANE:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_resetStayInLane;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_STAY_AWAY:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_stayAway;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_RESET_STAY_AWAY:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_resetStayAway;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_FOLLOW_ME:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_followMe;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_EXISTING_GROUP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_existingGroup;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_TEMPORARILY_DISBAND_AN_EXISTING_GROUP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_temporarilyDisbandAnExistingGroup;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_CONSTITUTE_A_TEMPORARILY_GROUP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_constituteATemporarilyGroup;
    break;
  case mcm_msgs::SubmanoeuvreStrategy::CHOICE_DISBAND_A_TEMPORARILY_GROUP:
    out.present = mcm_SubmanoeuvreStrategy_PR::mcm_SubmanoeuvreStrategy_PR_disbandATemporarilyGroup;
    break;
  default: break;
  }
}

}
