/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/mcm_custom/MCM.asn \
  asn1/raw/mcm_custom/ETSI-ITS-CDD.asn \
  -t \
  mcm \
  -o \
  etsi_its_conversion/etsi_its_mcm_conversion/include/etsi_its_mcm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This type represents the Manoeuvre Coordination Block at a given facility.
 *
 * It shall include the following components:
 *
 * @field header: the header of the MCM PDU,
 *
 * @field mcm: the payload of the MCM PDU,
*
ManoeuvreCoordinationRational ::= CHOICE {
	manoeuvreCooperationGoal ManoeuvreCooperationGoal, 	-- Only in case of prescriptive concept
	manoeuvreCooperationCost ManoeuvreCooperationCost	-- Only in case of agreement seeking
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_coding/mcm_ManoeuvreCoordinationRational.h>
#include <etsi_its_mcm_conversion/convertManoeuvreCooperationCost.h>
#include <etsi_its_mcm_conversion/convertManoeuvreCooperationGoal.h>
#include <etsi_its_mcm_msgs/msg/manoeuvre_coordination_rational.hpp>
namespace mcm_msgs = etsi_its_mcm_msgs::msg;


namespace etsi_its_mcm_conversion {

void toRos_ManoeuvreCoordinationRational(const mcm_ManoeuvreCoordinationRational_t& in, mcm_msgs::ManoeuvreCoordinationRational& out) {
  switch (in.present) {
  case mcm_ManoeuvreCoordinationRational_PR_manoeuvreCooperationGoal:
    toRos_ManoeuvreCooperationGoal(in.choice.manoeuvreCooperationGoal, out.manoeuvre_cooperation_goal);
    out.choice = mcm_msgs::ManoeuvreCoordinationRational::CHOICE_MANOEUVRE_COOPERATION_GOAL;
    break;
  case mcm_ManoeuvreCoordinationRational_PR_manoeuvreCooperationCost:
    toRos_ManoeuvreCooperationCost(in.choice.manoeuvreCooperationCost, out.manoeuvre_cooperation_cost);
    out.choice = mcm_msgs::ManoeuvreCoordinationRational::CHOICE_MANOEUVRE_COOPERATION_COST;
    break;
  default: break;
  }
}

void toStruct_ManoeuvreCoordinationRational(const mcm_msgs::ManoeuvreCoordinationRational& in, mcm_ManoeuvreCoordinationRational_t& out) {
  memset(&out, 0, sizeof(mcm_ManoeuvreCoordinationRational_t));
  switch (in.choice) {
  case mcm_msgs::ManoeuvreCoordinationRational::CHOICE_MANOEUVRE_COOPERATION_GOAL:
    toStruct_ManoeuvreCooperationGoal(in.manoeuvre_cooperation_goal, out.choice.manoeuvreCooperationGoal);
    out.present = mcm_ManoeuvreCoordinationRational_PR::mcm_ManoeuvreCoordinationRational_PR_manoeuvreCooperationGoal;
    break;
  case mcm_msgs::ManoeuvreCoordinationRational::CHOICE_MANOEUVRE_COOPERATION_COST:
    toStruct_ManoeuvreCooperationCost(in.manoeuvre_cooperation_cost, out.choice.manoeuvreCooperationCost);
    out.present = mcm_ManoeuvreCoordinationRational_PR::mcm_ManoeuvreCoordinationRational_PR_manoeuvreCooperationCost;
    break;
  default: break;
  }
}

}
