/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "/input/DENM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_denm_ShortTermConstructionSiteContainer_H_
#define	_denm_ShortTermConstructionSiteContainer_H_


#include <etsi_its_denm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_denm_coding/denm_ReferencePosition.h"
#include "etsi_its_denm_coding/denm_DeltaReferencePosition.h"
#include "etsi_its_denm_coding/denm_StationID.h"
#include <etsi_its_denm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_denm_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_denm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct denm_DeltaReferencePosition;

/* denm_ShortTermConstructionSiteContainer */
typedef struct denm_ShortTermConstructionSiteContainer {
	denm_ReferencePosition_t	 beginOfConstructionSite;
	denm_DeltaReferencePosition_t	 endOfConstructionSite;
	struct denm_ShortTermConstructionSiteContainer__deltaPolygonPoints {
		A_SEQUENCE_OF(struct denm_DeltaReferencePosition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} deltaPolygonPoints;
	denm_StationID_t	*accidentVehicleStationId;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} denm_ShortTermConstructionSiteContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_denm_ShortTermConstructionSiteContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_denm_ShortTermConstructionSiteContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_denm_ShortTermConstructionSiteContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_denm_coding/denm_DeltaReferencePosition.h"

#endif	/* _denm_ShortTermConstructionSiteContainer_H_ */
#include <etsi_its_denm_coding/asn_internal.h>
