/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_VehicleIdentification_H_
#define	_asm_VehicleIdentification_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_WMInumber.h"
#include "etsi_its_asm_coding/asm_VDS.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_VehicleIdentification */
typedef struct asm_VehicleIdentification {
	asm_WMInumber_t	*wMInumber;	/* OPTIONAL */
	asm_VDS_t	*vDS;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_VehicleIdentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_VehicleIdentification;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_VehicleIdentification_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
