/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DangerousSituationSubCauseCode_H_
#define	_asm_DangerousSituationSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_DangerousSituationSubCauseCode {
	asm_DangerousSituationSubCauseCode_unavailable	= 0,
	asm_DangerousSituationSubCauseCode_emergencyElectronicBrakeEngaged	= 1,
	asm_DangerousSituationSubCauseCode_preCrashSystemEngaged	= 2,
	asm_DangerousSituationSubCauseCode_espEngaged	= 3,
	asm_DangerousSituationSubCauseCode_absEngaged	= 4,
	asm_DangerousSituationSubCauseCode_aebEngaged	= 5,
	asm_DangerousSituationSubCauseCode_brakeWarningEngaged	= 6,
	asm_DangerousSituationSubCauseCode_collisionRiskWarningEngaged	= 7
} e_asm_DangerousSituationSubCauseCode;

/* asm_DangerousSituationSubCauseCode */
typedef long	 asm_DangerousSituationSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_DangerousSituationSubCauseCode;
asn_struct_free_f asm_DangerousSituationSubCauseCode_free;
asn_struct_print_f asm_DangerousSituationSubCauseCode_print;
asn_constr_check_f asm_DangerousSituationSubCauseCode_constraint;
jer_type_encoder_f asm_DangerousSituationSubCauseCode_encode_jer;
per_type_decoder_f asm_DangerousSituationSubCauseCode_decode_uper;
per_type_encoder_f asm_DangerousSituationSubCauseCode_encode_uper;
per_type_decoder_f asm_DangerousSituationSubCauseCode_decode_aper;
per_type_encoder_f asm_DangerousSituationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_DangerousSituationSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
