/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_CenDsrcTollingZone_H_
#define	_asm_CenDsrcTollingZone_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_Latitude.h"
#include "etsi_its_asm_coding/asm_Longitude.h"
#include "etsi_its_asm_coding/asm_CenDsrcTollingZoneID.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_CenDsrcTollingZone */
typedef struct asm_CenDsrcTollingZone {
	asm_Latitude_t	 protectedZoneLatitude;
	asm_Longitude_t	 protectedZoneLongitude;
	asm_CenDsrcTollingZoneID_t	*cenDsrcTollingZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_CenDsrcTollingZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_CenDsrcTollingZone;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_CenDsrcTollingZone_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
