/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_PosConfidenceEllipse_H_
#define	_asm_PosConfidenceEllipse_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_SemiAxisLength.h"
#include "etsi_its_asm_coding/asm_HeadingValue.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_PosConfidenceEllipse */
typedef struct asm_PosConfidenceEllipse {
	asm_SemiAxisLength_t	 semiMajorConfidence;
	asm_SemiAxisLength_t	 semiMinorConfidence;
	asm_HeadingValue_t	 semiMajorOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_PosConfidenceEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_PosConfidenceEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_PosConfidenceEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_PosConfidenceEllipse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_PosConfidenceEllipse_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
