/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_PostCrashSubCauseCode_H_
#define	_asm_PostCrashSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_PostCrashSubCauseCode {
	asm_PostCrashSubCauseCode_unavailable	= 0,
	asm_PostCrashSubCauseCode_accidentWithoutECallTriggered	= 1,
	asm_PostCrashSubCauseCode_accidentWithECallManuallyTriggered	= 2,
	asm_PostCrashSubCauseCode_accidentWithECallAutomaticallyTriggered	= 3,
	asm_PostCrashSubCauseCode_accidentWithECallTriggeredWithoutAccessToCellularNetwork	= 4
} e_asm_PostCrashSubCauseCode;

/* asm_PostCrashSubCauseCode */
typedef long	 asm_PostCrashSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_PostCrashSubCauseCode;
asn_struct_free_f asm_PostCrashSubCauseCode_free;
asn_struct_print_f asm_PostCrashSubCauseCode_print;
asn_constr_check_f asm_PostCrashSubCauseCode_constraint;
jer_type_encoder_f asm_PostCrashSubCauseCode_encode_jer;
per_type_decoder_f asm_PostCrashSubCauseCode_decode_uper;
per_type_encoder_f asm_PostCrashSubCauseCode_encode_uper;
per_type_decoder_f asm_PostCrashSubCauseCode_decode_aper;
per_type_encoder_f asm_PostCrashSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_PostCrashSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
