/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_Altitude_H_
#define	_asm_Altitude_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_AltitudeValue.h"
#include "etsi_its_asm_coding/asm_AltitudeConfidence.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_Altitude */
typedef struct asm_Altitude {
	asm_AltitudeValue_t	 altitudeValue;
	asm_AltitudeConfidence_t	 altitudeConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_Altitude;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_Altitude_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_Altitude_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_Altitude_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
