/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_TrafficConditionSubCauseCode_H_
#define	_asm_TrafficConditionSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_TrafficConditionSubCauseCode {
	asm_TrafficConditionSubCauseCode_unavailable	= 0,
	asm_TrafficConditionSubCauseCode_increasedVolumeOfTraffic	= 1,
	asm_TrafficConditionSubCauseCode_trafficJamSlowlyIncreasing	= 2,
	asm_TrafficConditionSubCauseCode_trafficJamIncreasing	= 3,
	asm_TrafficConditionSubCauseCode_trafficJamStronglyIncreasing	= 4,
	asm_TrafficConditionSubCauseCode_trafficStationary	= 5,
	asm_TrafficConditionSubCauseCode_trafficJamSlightlyDecreasing	= 6,
	asm_TrafficConditionSubCauseCode_trafficJamDecreasing	= 7,
	asm_TrafficConditionSubCauseCode_trafficJamStronglyDecreasing	= 8
} e_asm_TrafficConditionSubCauseCode;

/* asm_TrafficConditionSubCauseCode */
typedef long	 asm_TrafficConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_TrafficConditionSubCauseCode;
asn_struct_free_f asm_TrafficConditionSubCauseCode_free;
asn_struct_print_f asm_TrafficConditionSubCauseCode_print;
asn_constr_check_f asm_TrafficConditionSubCauseCode_constraint;
jer_type_encoder_f asm_TrafficConditionSubCauseCode_encode_jer;
per_type_decoder_f asm_TrafficConditionSubCauseCode_decode_uper;
per_type_encoder_f asm_TrafficConditionSubCauseCode_encode_uper;
per_type_decoder_f asm_TrafficConditionSubCauseCode_decode_aper;
per_type_encoder_f asm_TrafficConditionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_TrafficConditionSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
