/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_ProtectedCommunicationZone_H_
#define	_asm_ProtectedCommunicationZone_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_ProtectedZoneType.h"
#include "etsi_its_asm_coding/asm_TimestampIts.h"
#include "etsi_its_asm_coding/asm_Latitude.h"
#include "etsi_its_asm_coding/asm_Longitude.h"
#include "etsi_its_asm_coding/asm_ProtectedZoneRadius.h"
#include "etsi_its_asm_coding/asm_ProtectedZoneID.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_ProtectedCommunicationZone */
typedef struct asm_ProtectedCommunicationZone {
	asm_ProtectedZoneType_t	 protectedZoneType;
	asm_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	asm_Latitude_t	 protectedZoneLatitude;
	asm_Longitude_t	 protectedZoneLongitude;
	asm_ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	asm_ProtectedZoneID_t	*protectedZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_ProtectedCommunicationZone_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
