/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_HardShoulderStatus_H_
#define	_asm_HardShoulderStatus_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_HardShoulderStatus {
	asm_HardShoulderStatus_availableForStopping	= 0,
	asm_HardShoulderStatus_closed	= 1,
	asm_HardShoulderStatus_availableForDriving	= 2
} e_asm_HardShoulderStatus;

/* asm_HardShoulderStatus */
typedef long	 asm_HardShoulderStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_HardShoulderStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_HardShoulderStatus;
extern const asn_INTEGER_specifics_t asn_SPC_asm_HardShoulderStatus_specs_1;
asn_struct_free_f asm_HardShoulderStatus_free;
asn_struct_print_f asm_HardShoulderStatus_print;
asn_constr_check_f asm_HardShoulderStatus_constraint;
jer_type_encoder_f asm_HardShoulderStatus_encode_jer;
per_type_decoder_f asm_HardShoulderStatus_decode_uper;
per_type_encoder_f asm_HardShoulderStatus_encode_uper;
per_type_decoder_f asm_HardShoulderStatus_decode_aper;
per_type_encoder_f asm_HardShoulderStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_HardShoulderStatus_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
