/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_PhoneNumber_H_
#define	_asm_PhoneNumber_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_PhoneNumber */
typedef NumericString_t	 asm_PhoneNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_PhoneNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_PhoneNumber;
asn_struct_free_f asm_PhoneNumber_free;
asn_struct_print_f asm_PhoneNumber_print;
asn_constr_check_f asm_PhoneNumber_constraint;
jer_type_encoder_f asm_PhoneNumber_encode_jer;
per_type_decoder_f asm_PhoneNumber_decode_uper;
per_type_encoder_f asm_PhoneNumber_encode_uper;
per_type_decoder_f asm_PhoneNumber_decode_aper;
per_type_encoder_f asm_PhoneNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_PhoneNumber_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
