/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_VehicleBreakdownSubCauseCode_H_
#define	_asm_VehicleBreakdownSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_VehicleBreakdownSubCauseCode {
	asm_VehicleBreakdownSubCauseCode_unavailable	= 0,
	asm_VehicleBreakdownSubCauseCode_lackOfFuel	= 1,
	asm_VehicleBreakdownSubCauseCode_lackOfBatteryPower	= 2,
	asm_VehicleBreakdownSubCauseCode_engineProblem	= 3,
	asm_VehicleBreakdownSubCauseCode_transmissionProblem	= 4,
	asm_VehicleBreakdownSubCauseCode_engineCoolingProblem	= 5,
	asm_VehicleBreakdownSubCauseCode_brakingSystemProblem	= 6,
	asm_VehicleBreakdownSubCauseCode_steeringProblem	= 7,
	asm_VehicleBreakdownSubCauseCode_tyrePuncture	= 8,
	asm_VehicleBreakdownSubCauseCode_tyrePressureProblem	= 9
} e_asm_VehicleBreakdownSubCauseCode;

/* asm_VehicleBreakdownSubCauseCode */
typedef long	 asm_VehicleBreakdownSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_VehicleBreakdownSubCauseCode;
asn_struct_free_f asm_VehicleBreakdownSubCauseCode_free;
asn_struct_print_f asm_VehicleBreakdownSubCauseCode_print;
asn_constr_check_f asm_VehicleBreakdownSubCauseCode_constraint;
jer_type_encoder_f asm_VehicleBreakdownSubCauseCode_encode_jer;
per_type_decoder_f asm_VehicleBreakdownSubCauseCode_decode_uper;
per_type_encoder_f asm_VehicleBreakdownSubCauseCode_encode_uper;
per_type_decoder_f asm_VehicleBreakdownSubCauseCode_decode_aper;
per_type_encoder_f asm_VehicleBreakdownSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_VehicleBreakdownSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
