/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_SteeringWheelAngleValue_H_
#define	_asm_SteeringWheelAngleValue_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_SteeringWheelAngleValue {
	asm_SteeringWheelAngleValue_straight	= 0,
	asm_SteeringWheelAngleValue_onePointFiveDegreesToRight	= -1,
	asm_SteeringWheelAngleValue_onePointFiveDegreesToLeft	= 1,
	asm_SteeringWheelAngleValue_unavailable	= 512
} e_asm_SteeringWheelAngleValue;

/* asm_SteeringWheelAngleValue */
typedef long	 asm_SteeringWheelAngleValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_SteeringWheelAngleValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_SteeringWheelAngleValue;
asn_struct_free_f asm_SteeringWheelAngleValue_free;
asn_struct_print_f asm_SteeringWheelAngleValue_print;
asn_constr_check_f asm_SteeringWheelAngleValue_constraint;
jer_type_encoder_f asm_SteeringWheelAngleValue_encode_jer;
per_type_decoder_f asm_SteeringWheelAngleValue_decode_uper;
per_type_encoder_f asm_SteeringWheelAngleValue_encode_uper;
per_type_decoder_f asm_SteeringWheelAngleValue_decode_aper;
per_type_encoder_f asm_SteeringWheelAngleValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_SteeringWheelAngleValue_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
