/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_AccelerationControl_H_
#define	_asm_AccelerationControl_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_AccelerationControl {
	asm_AccelerationControl_brakePedalEngaged	= 0,
	asm_AccelerationControl_gasPedalEngaged	= 1,
	asm_AccelerationControl_emergencyBrakeEngaged	= 2,
	asm_AccelerationControl_collisionWarningEngaged	= 3,
	asm_AccelerationControl_accEngaged	= 4,
	asm_AccelerationControl_cruiseControlEngaged	= 5,
	asm_AccelerationControl_speedLimiterEngaged	= 6
} e_asm_AccelerationControl;

/* asm_AccelerationControl */
typedef BIT_STRING_t	 asm_AccelerationControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_AccelerationControl;
asn_struct_free_f asm_AccelerationControl_free;
asn_struct_print_f asm_AccelerationControl_print;
asn_constr_check_f asm_AccelerationControl_constraint;
jer_type_encoder_f asm_AccelerationControl_encode_jer;
per_type_decoder_f asm_AccelerationControl_decode_uper;
per_type_encoder_f asm_AccelerationControl_encode_uper;
per_type_decoder_f asm_AccelerationControl_decode_aper;
per_type_encoder_f asm_AccelerationControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_AccelerationControl_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
