/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_EmbarkationStatus_H_
#define	_asm_EmbarkationStatus_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_EmbarkationStatus */
typedef BOOLEAN_t	 asm_EmbarkationStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_EmbarkationStatus;
asn_struct_free_f asm_EmbarkationStatus_free;
asn_struct_print_f asm_EmbarkationStatus_print;
asn_constr_check_f asm_EmbarkationStatus_constraint;
jer_type_encoder_f asm_EmbarkationStatus_encode_jer;
per_type_decoder_f asm_EmbarkationStatus_decode_uper;
per_type_encoder_f asm_EmbarkationStatus_encode_uper;
per_type_decoder_f asm_EmbarkationStatus_decode_aper;
per_type_encoder_f asm_EmbarkationStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_EmbarkationStatus_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
