/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DangerousGoodsExtended_H_
#define	_asm_DangerousGoodsExtended_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_DangerousGoodsBasic.h"
#include <etsi_its_asm_coding/NativeInteger.h>
#include <etsi_its_asm_coding/BOOLEAN.h>
#include <etsi_its_asm_coding/IA5String.h>
#include "etsi_its_asm_coding/asm_PhoneNumber.h"
#include <etsi_its_asm_coding/UTF8String.h>
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_DangerousGoodsExtended */
typedef struct asm_DangerousGoodsExtended {
	asm_DangerousGoodsBasic_t	 dangerousGoodsType;
	long	 unNumber;
	BOOLEAN_t	 elevatedTemperature;
	BOOLEAN_t	 tunnelsRestricted;
	BOOLEAN_t	 limitedQuantity;
	IA5String_t	*emergencyActionCode;	/* OPTIONAL */
	asm_PhoneNumber_t	*phoneNumber;	/* OPTIONAL */
	UTF8String_t	*companyName;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_DangerousGoodsExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_DangerousGoodsExtended;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_DangerousGoodsExtended_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
