/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_LateralAccelerationValue_H_
#define	_asm_LateralAccelerationValue_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_LateralAccelerationValue {
	asm_LateralAccelerationValue_pointOneMeterPerSecSquaredToRight	= -1,
	asm_LateralAccelerationValue_pointOneMeterPerSecSquaredToLeft	= 1,
	asm_LateralAccelerationValue_unavailable	= 161
} e_asm_LateralAccelerationValue;

/* asm_LateralAccelerationValue */
typedef long	 asm_LateralAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_LateralAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_LateralAccelerationValue;
asn_struct_free_f asm_LateralAccelerationValue_free;
asn_struct_print_f asm_LateralAccelerationValue_print;
asn_constr_check_f asm_LateralAccelerationValue_constraint;
jer_type_encoder_f asm_LateralAccelerationValue_encode_jer;
per_type_decoder_f asm_LateralAccelerationValue_decode_uper;
per_type_encoder_f asm_LateralAccelerationValue_encode_uper;
per_type_decoder_f asm_LateralAccelerationValue_decode_aper;
per_type_encoder_f asm_LateralAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_LateralAccelerationValue_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
