/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_CauseCodeType_H_
#define	_asm_CauseCodeType_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_CauseCodeType {
	asm_CauseCodeType_reserved	= 0,
	asm_CauseCodeType_trafficCondition	= 1,
	asm_CauseCodeType_accident	= 2,
	asm_CauseCodeType_roadworks	= 3,
	asm_CauseCodeType_impassability	= 5,
	asm_CauseCodeType_adverseWeatherCondition_Adhesion	= 6,
	asm_CauseCodeType_aquaplannning	= 7,
	asm_CauseCodeType_hazardousLocation_SurfaceCondition	= 9,
	asm_CauseCodeType_hazardousLocation_ObstacleOnTheRoad	= 10,
	asm_CauseCodeType_hazardousLocation_AnimalOnTheRoad	= 11,
	asm_CauseCodeType_humanPresenceOnTheRoad	= 12,
	asm_CauseCodeType_wrongWayDriving	= 14,
	asm_CauseCodeType_rescueAndRecoveryWorkInProgress	= 15,
	asm_CauseCodeType_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	asm_CauseCodeType_adverseWeatherCondition_Visibility	= 18,
	asm_CauseCodeType_adverseWeatherCondition_Precipitation	= 19,
	asm_CauseCodeType_slowVehicle	= 26,
	asm_CauseCodeType_dangerousEndOfQueue	= 27,
	asm_CauseCodeType_vehicleBreakdown	= 91,
	asm_CauseCodeType_postCrash	= 92,
	asm_CauseCodeType_humanProblem	= 93,
	asm_CauseCodeType_stationaryVehicle	= 94,
	asm_CauseCodeType_emergencyVehicleApproaching	= 95,
	asm_CauseCodeType_hazardousLocation_DangerousCurve	= 96,
	asm_CauseCodeType_collisionRisk	= 97,
	asm_CauseCodeType_signalViolation	= 98,
	asm_CauseCodeType_dangerousSituation	= 99
} e_asm_CauseCodeType;

/* asm_CauseCodeType */
typedef long	 asm_CauseCodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_CauseCodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_CauseCodeType;
asn_struct_free_f asm_CauseCodeType_free;
asn_struct_print_f asm_CauseCodeType_print;
asn_constr_check_f asm_CauseCodeType_constraint;
jer_type_encoder_f asm_CauseCodeType_encode_jer;
per_type_decoder_f asm_CauseCodeType_decode_uper;
per_type_encoder_f asm_CauseCodeType_encode_uper;
per_type_decoder_f asm_CauseCodeType_decode_aper;
per_type_encoder_f asm_CauseCodeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_CauseCodeType_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
