/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_Heading_H_
#define	_asm_Heading_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_HeadingValue.h"
#include "etsi_its_asm_coding/asm_HeadingConfidence.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_Heading */
typedef struct asm_Heading {
	asm_HeadingValue_t	 headingValue;
	asm_HeadingConfidence_t	 headingConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_Heading_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_Heading;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_Heading_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
