/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DangerousEndOfQueueSubCauseCode_H_
#define	_asm_DangerousEndOfQueueSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_DangerousEndOfQueueSubCauseCode {
	asm_DangerousEndOfQueueSubCauseCode_unavailable	= 0,
	asm_DangerousEndOfQueueSubCauseCode_suddenEndOfQueue	= 1,
	asm_DangerousEndOfQueueSubCauseCode_queueOverHill	= 2,
	asm_DangerousEndOfQueueSubCauseCode_queueAroundBend	= 3,
	asm_DangerousEndOfQueueSubCauseCode_queueInTunnel	= 4
} e_asm_DangerousEndOfQueueSubCauseCode;

/* asm_DangerousEndOfQueueSubCauseCode */
typedef long	 asm_DangerousEndOfQueueSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_DangerousEndOfQueueSubCauseCode;
asn_struct_free_f asm_DangerousEndOfQueueSubCauseCode_free;
asn_struct_print_f asm_DangerousEndOfQueueSubCauseCode_print;
asn_constr_check_f asm_DangerousEndOfQueueSubCauseCode_constraint;
jer_type_encoder_f asm_DangerousEndOfQueueSubCauseCode_encode_jer;
per_type_decoder_f asm_DangerousEndOfQueueSubCauseCode_decode_uper;
per_type_encoder_f asm_DangerousEndOfQueueSubCauseCode_encode_uper;
per_type_decoder_f asm_DangerousEndOfQueueSubCauseCode_decode_aper;
per_type_encoder_f asm_DangerousEndOfQueueSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_DangerousEndOfQueueSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
