/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ASM-PDU-Descriptions"
 * 	found in "/input/ASM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_ApplicationSpecificMessage_H_
#define	_asm_ApplicationSpecificMessage_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_ApplicationSpecificData.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_ApplicationSpecificMessage */
typedef struct asm_ApplicationSpecificMessage {
	asm_ApplicationSpecificData_t	 data;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_ApplicationSpecificMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_ApplicationSpecificMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_ApplicationSpecificMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_ApplicationSpecificMessage_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_ApplicationSpecificMessage_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
