/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DigitalMap_H_
#define	_asm_DigitalMap_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_asm_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asm_ReferencePosition;

/* asm_DigitalMap */
typedef struct asm_DigitalMap {
	A_SEQUENCE_OF(struct asm_ReferencePosition) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_DigitalMap_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_DigitalMap;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_asm_coding/asm_ReferencePosition.h"

#endif	/* _asm_DigitalMap_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
