/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_CauseCode_H_
#define	_asm_CauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_CauseCodeType.h"
#include "etsi_its_asm_coding/asm_SubCauseCodeType.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_CauseCode */
typedef struct asm_CauseCode {
	asm_CauseCodeType_t	 causeCode;
	asm_SubCauseCodeType_t	 subCauseCode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_CauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_CauseCode;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_CauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
