/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_EmergencyPriority_H_
#define	_asm_EmergencyPriority_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_EmergencyPriority {
	asm_EmergencyPriority_requestForRightOfWay	= 0,
	asm_EmergencyPriority_requestForFreeCrossingAtATrafficLight	= 1
} e_asm_EmergencyPriority;

/* asm_EmergencyPriority */
typedef BIT_STRING_t	 asm_EmergencyPriority_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_EmergencyPriority;
asn_struct_free_f asm_EmergencyPriority_free;
asn_struct_print_f asm_EmergencyPriority_print;
asn_constr_check_f asm_EmergencyPriority_constraint;
jer_type_encoder_f asm_EmergencyPriority_encode_jer;
per_type_decoder_f asm_EmergencyPriority_decode_uper;
per_type_encoder_f asm_EmergencyPriority_encode_uper;
per_type_decoder_f asm_EmergencyPriority_decode_aper;
per_type_encoder_f asm_EmergencyPriority_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_EmergencyPriority_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
