/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_HazardousLocation_SurfaceConditionSubCauseCode_H_
#define	_asm_HazardousLocation_SurfaceConditionSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_HazardousLocation_SurfaceConditionSubCauseCode {
	asm_HazardousLocation_SurfaceConditionSubCauseCode_unavailable	= 0,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_rockfalls	= 1,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_earthquakeDamage	= 2,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_sewerCollapse	= 3,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_subsidence	= 4,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_snowDrifts	= 5,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_stormDamage	= 6,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_burstPipe	= 7,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_volcanoEruption	= 8,
	asm_HazardousLocation_SurfaceConditionSubCauseCode_fallingIce	= 9
} e_asm_HazardousLocation_SurfaceConditionSubCauseCode;

/* asm_HazardousLocation-SurfaceConditionSubCauseCode */
typedef long	 asm_HazardousLocation_SurfaceConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_HazardousLocation_SurfaceConditionSubCauseCode;
asn_struct_free_f asm_HazardousLocation_SurfaceConditionSubCauseCode_free;
asn_struct_print_f asm_HazardousLocation_SurfaceConditionSubCauseCode_print;
asn_constr_check_f asm_HazardousLocation_SurfaceConditionSubCauseCode_constraint;
jer_type_encoder_f asm_HazardousLocation_SurfaceConditionSubCauseCode_encode_jer;
per_type_decoder_f asm_HazardousLocation_SurfaceConditionSubCauseCode_decode_uper;
per_type_encoder_f asm_HazardousLocation_SurfaceConditionSubCauseCode_encode_uper;
per_type_decoder_f asm_HazardousLocation_SurfaceConditionSubCauseCode_decode_aper;
per_type_encoder_f asm_HazardousLocation_SurfaceConditionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_HazardousLocation_SurfaceConditionSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
