/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_AdverseWeatherCondition_AdhesionSubCauseCode_H_
#define	_asm_AdverseWeatherCondition_AdhesionSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_AdverseWeatherCondition_AdhesionSubCauseCode {
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_unavailable	= 0,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_heavyFrostOnRoad	= 1,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_fuelOnRoad	= 2,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_mudOnRoad	= 3,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_snowOnRoad	= 4,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_iceOnRoad	= 5,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_blackIceOnRoad	= 6,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_oilOnRoad	= 7,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_looseChippings	= 8,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_instantBlackIce	= 9,
	asm_AdverseWeatherCondition_AdhesionSubCauseCode_roadsSalted	= 10
} e_asm_AdverseWeatherCondition_AdhesionSubCauseCode;

/* asm_AdverseWeatherCondition-AdhesionSubCauseCode */
typedef long	 asm_AdverseWeatherCondition_AdhesionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_AdverseWeatherCondition_AdhesionSubCauseCode;
asn_struct_free_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_free;
asn_struct_print_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_print;
asn_constr_check_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_constraint;
jer_type_encoder_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_jer;
per_type_decoder_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_decode_uper;
per_type_encoder_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_uper;
per_type_decoder_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_decode_aper;
per_type_encoder_f asm_AdverseWeatherCondition_AdhesionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_AdverseWeatherCondition_AdhesionSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
