/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_LightBarSirenInUse_H_
#define	_asm_LightBarSirenInUse_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_LightBarSirenInUse {
	asm_LightBarSirenInUse_lightBarActivated	= 0,
	asm_LightBarSirenInUse_sirenActivated	= 1
} e_asm_LightBarSirenInUse;

/* asm_LightBarSirenInUse */
typedef BIT_STRING_t	 asm_LightBarSirenInUse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_LightBarSirenInUse;
asn_struct_free_f asm_LightBarSirenInUse_free;
asn_struct_print_f asm_LightBarSirenInUse_print;
asn_constr_check_f asm_LightBarSirenInUse_constraint;
jer_type_encoder_f asm_LightBarSirenInUse_encode_jer;
per_type_decoder_f asm_LightBarSirenInUse_decode_uper;
per_type_encoder_f asm_LightBarSirenInUse_encode_uper;
per_type_decoder_f asm_LightBarSirenInUse_decode_aper;
per_type_encoder_f asm_LightBarSirenInUse_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_LightBarSirenInUse_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
