/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ASM-PDU-Descriptions"
 * 	found in "/input/ASM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_ASM_H_
#define	_asm_ASM_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_ItsPduHeader.h"
#include "etsi_its_asm_coding/asm_TimestampIts.h"
#include "etsi_its_asm_coding/asm_ApplicationIdentifier.h"
#include "etsi_its_asm_coding/asm_ApplicationSpecificMessage.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_ASM */
typedef struct asm_ASM {
	asm_ItsPduHeader_t	 header;
	asm_TimestampIts_t	 generationTime;
	asm_ApplicationIdentifier_t	 applicationIdentifier;
	asm_ApplicationSpecificMessage_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_ASM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_ASM;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_ASM_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
