/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_CurvatureCalculationMode_H_
#define	_asm_CurvatureCalculationMode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_CurvatureCalculationMode {
	asm_CurvatureCalculationMode_yawRateUsed	= 0,
	asm_CurvatureCalculationMode_yawRateNotUsed	= 1,
	asm_CurvatureCalculationMode_unavailable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_asm_CurvatureCalculationMode;

/* asm_CurvatureCalculationMode */
typedef long	 asm_CurvatureCalculationMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_CurvatureCalculationMode;
asn_struct_free_f asm_CurvatureCalculationMode_free;
asn_struct_print_f asm_CurvatureCalculationMode_print;
asn_constr_check_f asm_CurvatureCalculationMode_constraint;
jer_type_encoder_f asm_CurvatureCalculationMode_encode_jer;
per_type_decoder_f asm_CurvatureCalculationMode_decode_uper;
per_type_encoder_f asm_CurvatureCalculationMode_encode_uper;
per_type_decoder_f asm_CurvatureCalculationMode_decode_aper;
per_type_encoder_f asm_CurvatureCalculationMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_CurvatureCalculationMode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
