/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DeltaReferencePosition_H_
#define	_asm_DeltaReferencePosition_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_DeltaLatitude.h"
#include "etsi_its_asm_coding/asm_DeltaLongitude.h"
#include "etsi_its_asm_coding/asm_DeltaAltitude.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_DeltaReferencePosition */
typedef struct asm_DeltaReferencePosition {
	asm_DeltaLatitude_t	 deltaLatitude;
	asm_DeltaLongitude_t	 deltaLongitude;
	asm_DeltaAltitude_t	 deltaAltitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_DeltaReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_DeltaReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_DeltaReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_DeltaReferencePosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_DeltaReferencePosition_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
