/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_ItsPduHeader_H_
#define	_asm_ItsPduHeader_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>
#include "etsi_its_asm_coding/asm_StationID.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_ItsPduHeader__messageID {
	asm_ItsPduHeader__messageID_denm	= 1,
	asm_ItsPduHeader__messageID_cam	= 2,
	asm_ItsPduHeader__messageID_poi	= 3,
	asm_ItsPduHeader__messageID_spatem	= 4,
	asm_ItsPduHeader__messageID_mapem	= 5,
	asm_ItsPduHeader__messageID_ivim	= 6,
	asm_ItsPduHeader__messageID_ev_rsr	= 7,
	asm_ItsPduHeader__messageID_tistpgtransaction	= 8,
	asm_ItsPduHeader__messageID_srem	= 9,
	asm_ItsPduHeader__messageID_ssem	= 10,
	asm_ItsPduHeader__messageID_evcsn	= 11,
	asm_ItsPduHeader__messageID_saem	= 12,
	asm_ItsPduHeader__messageID_rtcmem	= 13
} e_asm_ItsPduHeader__messageID;

/* asm_ItsPduHeader */
typedef struct asm_ItsPduHeader {
	long	 protocolVersion;
	long	 messageID;
	asm_StationID_t	 stationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_ItsPduHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_ItsPduHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_ItsPduHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_ItsPduHeader_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_ItsPduHeader_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
