/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_DangerousGoodsBasic_H_
#define	_asm_DangerousGoodsBasic_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_DangerousGoodsBasic {
	asm_DangerousGoodsBasic_explosives1	= 0,
	asm_DangerousGoodsBasic_explosives2	= 1,
	asm_DangerousGoodsBasic_explosives3	= 2,
	asm_DangerousGoodsBasic_explosives4	= 3,
	asm_DangerousGoodsBasic_explosives5	= 4,
	asm_DangerousGoodsBasic_explosives6	= 5,
	asm_DangerousGoodsBasic_flammableGases	= 6,
	asm_DangerousGoodsBasic_nonFlammableGases	= 7,
	asm_DangerousGoodsBasic_toxicGases	= 8,
	asm_DangerousGoodsBasic_flammableLiquids	= 9,
	asm_DangerousGoodsBasic_flammableSolids	= 10,
	asm_DangerousGoodsBasic_substancesLiableToSpontaneousCombustion	= 11,
	asm_DangerousGoodsBasic_substancesEmittingFlammableGasesUponContactWithWater	= 12,
	asm_DangerousGoodsBasic_oxidizingSubstances	= 13,
	asm_DangerousGoodsBasic_organicPeroxides	= 14,
	asm_DangerousGoodsBasic_toxicSubstances	= 15,
	asm_DangerousGoodsBasic_infectiousSubstances	= 16,
	asm_DangerousGoodsBasic_radioactiveMaterial	= 17,
	asm_DangerousGoodsBasic_corrosiveSubstances	= 18,
	asm_DangerousGoodsBasic_miscellaneousDangerousSubstances	= 19
} e_asm_DangerousGoodsBasic;

/* asm_DangerousGoodsBasic */
typedef long	 asm_DangerousGoodsBasic_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asm_DangerousGoodsBasic_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asm_DangerousGoodsBasic;
extern const asn_INTEGER_specifics_t asn_SPC_asm_DangerousGoodsBasic_specs_1;
asn_struct_free_f asm_DangerousGoodsBasic_free;
asn_struct_print_f asm_DangerousGoodsBasic_print;
asn_constr_check_f asm_DangerousGoodsBasic_constraint;
jer_type_encoder_f asm_DangerousGoodsBasic_encode_jer;
per_type_decoder_f asm_DangerousGoodsBasic_decode_uper;
per_type_encoder_f asm_DangerousGoodsBasic_encode_uper;
per_type_decoder_f asm_DangerousGoodsBasic_decode_aper;
per_type_encoder_f asm_DangerousGoodsBasic_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_DangerousGoodsBasic_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
