/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_EventPoint_H_
#define	_asm_EventPoint_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_DeltaReferencePosition.h"
#include "etsi_its_asm_coding/asm_PathDeltaTime.h"
#include "etsi_its_asm_coding/asm_InformationQuality.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_EventPoint */
typedef struct asm_EventPoint {
	asm_DeltaReferencePosition_t	 eventPosition;
	asm_PathDeltaTime_t	*eventDeltaTime;	/* OPTIONAL */
	asm_InformationQuality_t	 informationQuality;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_EventPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_EventPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_EventPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_EventPoint_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_EventPoint_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
