/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_ReferencePosition_H_
#define	_asm_ReferencePosition_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_asm_coding/asm_Latitude.h"
#include "etsi_its_asm_coding/asm_Longitude.h"
#include "etsi_its_asm_coding/asm_PosConfidenceEllipse.h"
#include "etsi_its_asm_coding/asm_Altitude.h"
#include <etsi_its_asm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asm_ReferencePosition */
typedef struct asm_ReferencePosition {
	asm_Latitude_t	 latitude;
	asm_Longitude_t	 longitude;
	asm_PosConfidenceEllipse_t	 positionConfidenceEllipse;
	asm_Altitude_t	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asm_ReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_ReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_asm_ReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_asm_ReferencePosition_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _asm_ReferencePosition_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
