/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_asm_RoadworksSubCauseCode_H_
#define	_asm_RoadworksSubCauseCode_H_


#include <etsi_its_asm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_asm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asm_RoadworksSubCauseCode {
	asm_RoadworksSubCauseCode_unavailable	= 0,
	asm_RoadworksSubCauseCode_majorRoadworks	= 1,
	asm_RoadworksSubCauseCode_roadMarkingWork	= 2,
	asm_RoadworksSubCauseCode_slowMovingRoadMaintenance	= 3,
	asm_RoadworksSubCauseCode_shortTermStationaryRoadworks	= 4,
	asm_RoadworksSubCauseCode_streetCleaning	= 5,
	asm_RoadworksSubCauseCode_winterService	= 6
} e_asm_RoadworksSubCauseCode;

/* asm_RoadworksSubCauseCode */
typedef long	 asm_RoadworksSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asm_RoadworksSubCauseCode;
asn_struct_free_f asm_RoadworksSubCauseCode_free;
asn_struct_print_f asm_RoadworksSubCauseCode_print;
asn_constr_check_f asm_RoadworksSubCauseCode_constraint;
jer_type_encoder_f asm_RoadworksSubCauseCode_encode_jer;
per_type_decoder_f asm_RoadworksSubCauseCode_decode_uper;
per_type_encoder_f asm_RoadworksSubCauseCode_encode_uper;
per_type_decoder_f asm_RoadworksSubCauseCode_decode_aper;
per_type_encoder_f asm_RoadworksSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asm_RoadworksSubCauseCode_H_ */
#include <etsi_its_asm_coding/asn_internal.h>
